<form>
    <div class="form-login">
        <div class="header">
            Đăng Nhập Hệ Thống
        </div>
        <div class="login-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email</label>
                        <input type="text" class="form-control" id="username">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Mật khẩu</label>
                        <input type="password" class="form-control" id="username">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"> Nhớ mật khẩu
                        </label>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="checkbox">
                        <a href="#" class="pull-right">Quên mật khẩu</a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                     <button type="submit" class="btn btn btn-info btn-login pull-right">Đăng nhập</button>
                </div>
            </div>
        </div>
    </div>
</form>