<form action="<?php echo $this->url('backend', array('controller' => 'public', 'action' => 'login')) ?>" method="post" enctype="multipart/form-data">
    <div class="form-login">
        <div class="header">
            Đăng Nhập Hệ Thống
        </div>
        <div class="login-content">
            <div class="row">
                <div class="col-lg-12"><p class="error"><?php echo isset($arrayParam['error'][0])? $arrayParam['error'][0]:'' ?></p></div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email" value="<?php echo isset($arrayParam['post']['email'])?$arrayParam['post']['email']:'' ?>">
                        <p class="error"><?php echo isset($arrayParam['error']['email'])? $arrayParam['error']['email']:'' ?></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label for="password">Mật khẩu</label>
                        <input type="password" class="form-control" id="password" name="password" value="<?php echo isset($arrayParam['post']['password'])?$arrayParam['post']['password']:'' ?>">
                        <p class="error"><?php echo isset($arrayParam['error']['password'])? $arrayParam['error']['password']:'' ?></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="rememberme"> Nhớ mật khẩu
                        </label>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <div class="checkbox">
                        <a href="#" class="pull-right">Quên mật khẩu</a>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                     <button type="submit" class="btn btn btn-info btn-login pull-right">Đăng nhập</button>
                </div>
            </div>
        </div>
    </div>
</form>