<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Nhóm <span>(Phân quyền)</span></h1>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'index')); ?>" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <select name="function" class="form-control selected-custom">
                                <option value="0">-- Chọn chức năng --</option>
                                <option value="1">1. Xóa</option>
                                <option value="2">2. Kích hoạt</option>
                                <option value="3">3. Ẩn </option>
                            </select>
                            <button type="submit" class="btn btn-default btn-custom apply">Thực hiện</button>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="db-function">
                            <button type="button" class="btn btn-default btn-custom update">Cập nhật</button>
                            <a href="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'add')); ?>" class="btn btn-default btn-custom add-news">Thêm mới</a>
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-table">
                                <?php if($list): ?>
                                <table id="table-data" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                            <th id="key" class="name column_name no-sort">
                                                Mã
                                            </th>
                                            <th id="name">
                                                Tên nhóm
                                            </th>
                                            <th class="description column_descripton">Mô tả</th>
                                            <th class="weight column_weight">Vị trí</th>
                                            <th class="quantity column_quantity">Trạng thái</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($list as $value): ?>
                                        <tr id="id-role-<?php echo $value['id']; ?>">
                                            <td><input <?php echo (in_array($value['id'], $listIdRole)) ? 'checked': '' ?> type="checkbox" value="<?php echo $value['id'];?>" name="check-all[]" class="form-checkbox check-all"></td>
                                            <td><?php echo $value['id']; ?></td>
                                            <td class="column-title column_name">
                                                <strong class="key-title"><?php echo $value['role_name']; ?></strong>
                                                <div class="row-action">
                                                    <span class="edit">
                                                        <a data-id="<?php echo $value['id']; ?>" href="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'edit', 'id' => $value['id'])); ?>">Sửa</a> | 
                                                    </span>
                                                    <span class="delete">
                                                        <a data-id="<?php echo $value['id']; ?>" data-toggle="modal" data-target=".modal-delete-role">Xóa</a> | 
                                                    </span>
                                                    <span class="view">
                                                        <a data-id="<?php echo $value['id']; ?>" href="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'rolepermission', 'id' => $value['id'])); ?>">Phân quyền</a>
                                                    </span>
                                                </div>
                                            </td>
                                            <td class="column_descripton"><?php echo $value['description']; ?></td>
                                            <td class="column_weight"><input type="number" data-id="<?php echo $value['id']; ?>" name="weight" min="0" max="9999" class="form-control" value="<?php echo $value['weight']; ?>"></td>
                                            <td class="column_status unstatus">
                                                <?php echo ($value['status'] == 1)? '<a data-status='.json_encode(array('id' => $value['id'], 'status' => 1)).' href="javascript:void(0)" title="Hiển thị" class="active fa fa-check-circle"></a>': '<a data-status='.json_encode(array('id' => $value['id'], 'status' => 0)).' title="Không hiển thị" class="unactive fa fa-minus-circle"></a>'; ?>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="modal fade modal-delete-role" tabindex="-1" role="dialog" aria-labelledby="modal-delete-role">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="gridSystemModalLabel">Bạn có muốn xóa không?</h4>
        </div>
        <div class="modal-footer">
            <input type="hidden" value="" name="id" id="modal-id-role" />
            <button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
            <button type="button" class="btn btn-primary" id="modal-delete-role">Xóa</button>
        </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){
        // delete
        $('.form-table .table>tbody>tr>td span.delete a').on('click', function(){
            var id = $(this).attr('data-id');
                $("#modal-id-role").val(id);
        });
        $("#modal-delete-role").on('click', function(){
            var id = $("#modal-id-role").val();
            if(id != '')
            {
                var obj = { 'id' : id};
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'delete')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    success: function(data){
                        $("#message-user").empty().append(data.message);
                        setTimeout(function(){
                            $('.modal-delete-role').modal('hide');
                            $("#id-role-"+id).remove();
                            $("#message-user").empty();
                        }, 500);
                        //location.reload();
                    }    
               });
            } 
        });
        
        // change status
        $(".form-table .table>tbody>tr>td.column_status a").on('click', function(){
            var data = $(this).attr('data-status');
            var loadData = jQuery.parseJSON(data);
            var obj = { 'id' : loadData.id, 'status': loadData.status };
            if (confirm('Bạn có muốn thay đổi trạng thái không?')) {
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'changestatus')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(){
                        location.reload();
                    }    
               });
            }   
        });
        // update weight
        $(".btn.btn-default.btn-custom.update").on('click', function(){
            var infoId = [];
            $("input[name='weight']").each(function(){
                infoId[$(this).attr('data-id')] = $(this).val();
            });
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'updateweight')) ?>",
                    data: {info: infoId},
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(data){
                        location.reload();
                    }    
               });
        });
        
        // delete 
//        $(".form-table .table>tbody>tr>td .row-action a").on('click', function(){
//            var id = $(this).attr('data-id');
//            var obj = { 'id' : id};
//            if (confirm('Bạn có muốn thay đổi trạng thái không?')) {
//                $.ajax({
//                    type:"POST",
//                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'changestatus')) ?>",
//                    data: obj,
//                    dataType: 'JSON',
//                    beforeSend: function(){
//                    },
//                    success: function(){
//                        location.reload();
//                    }    
//               });
//            }
//                
//        });
        
    });
</script>