<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Phân quyền <span>(nhóm)</span></h1>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'index')); ?>" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    
                    <div class="col-lg-12">
                        <div class="db-function">
                            <a href="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'index')); ?>" class="btn btn-default btn-custom back">Trở lại</a>
                            <button type="submit" class="btn btn-default btn-custom update">Lưu</button>
                            
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th><strong>Chức năng</strong></th>
                                        <th style="text-align: right" class="description column_descripton">Nhóm: <?php echo $arrayParam['rolename']['role_name']; ?></th>
                                    </tr>
                                    <tr>
                                        <td colspan="2" class="check-role">Tất cả <input type="checkbox" class="form-checkbox form-all"></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if($arrayParam['list']): ?>
                                        <?php foreach ($arrayParam['list'] as $key => $val): ?>
                                            <?php if(!empty(count($val['action']))):?>
                                                <tr>
                                                    <td colspan="2"><strong><?php echo $val['controller']; ?></strong></td>
                                                </tr>
                                                <?php foreach ($val['action'] as $key => $value): ?>
                                                <tr>
                                                    <td class="resource"><?php echo $value['name']; ?> <span>(<?php echo $value['description']? $value['description']: $val['module'] .'-'. $val['controller'].'-'.$value['name']; ?>)</span></td>
                                                    <td class="check-role" ><input <?php echo $value['flag']?'checked':''; ?> class="form-checkbox form-all" type="checkbox" name="role[<?php echo $arrayParam['role-id'] ?>]" value="<?php echo $value['id']; ?>" ></td>
                                                </tr>

                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="action-footer">
                            <div class="db-function">
                                <button type="submit" class="btn btn-default btn-custom update">Lưu</button>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</form>
<div class="modal fade modal-delete-role" tabindex="-1" role="dialog" aria-labelledby="modal-delete-role">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="gridSystemModalLabel">Bạn có muốn xóa không?</h4>
        </div>
        <div class="modal-footer">
            <input type="hidden" value="" name="id" id="modal-id-role" />
            <button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
            <button type="button" class="btn btn-primary" id="modal-delete-role">Xóa</button>
        </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){
        // delete
        $('.form-table .table>tbody>tr>td span.delete a').on('click', function(){
            var id = $(this).attr('data-id');
                $("#modal-id-role").val(id);
        });
        $("#modal-delete-role").on('click', function(){
            var id = $("#modal-id-role").val();
            alert(id);
            if(id != '')
            {
                var obj = { 'id' : id};
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'delete')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    success: function(data){
                        $("#message-user").empty().append(data.message);
                        setTimeout(function(){
                            $('.modal-delete-role').modal('hide');
                            $("#id-role-"+id).remove();
                            $("#message-user").empty();
                        }, 500);
                        //location.reload();
                    }    
               });
            } 
        });
        
        // change status
        $(".form-table .table>tbody>tr>td.column_status a").on('click', function(){
            var data = $(this).attr('data-status');
            var loadData = jQuery.parseJSON(data);
            var obj = { 'id' : loadData.id, 'status': loadData.status };
            if (confirm('Bạn có muốn thay đổi trạng thái không?')) {
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'changestatus')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(){
                        location.reload();
                    }    
               });
            }   
        });
        // update weight
        $(".btn.btn-default.btn-custom.update").on('click', function(){
            var infoId = [];
            $("input[name='weight']").each(function(){
                infoId[$(this).attr('data-id')] = $(this).val();
            });
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'updateweight')) ?>",
                    data: {info: infoId},
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(data){
                        location.reload();
                    }    
               });
        });
        
        // delete 
//        $(".form-table .table>tbody>tr>td .row-action a").on('click', function(){
//            var id = $(this).attr('data-id');
//            var obj = { 'id' : id};
//            if (confirm('Bạn có muốn thay đổi trạng thái không?')) {
//                $.ajax({
//                    type:"POST",
//                    url: "<?php echo $this->url($this->route, array('controller' => 'role', 'action' => 'changestatus')) ?>",
//                    data: obj,
//                    dataType: 'JSON',
//                    beforeSend: function(){
//                    },
//                    success: function(){
//                        location.reload();
//                    }    
//               });
//            }
//                
//        });
        
    });
</script>