<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Phân quyền <span>(nhóm)</span></h1>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'rolepermission', 'id' => $arrayParam['role-id'])); ?>" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    
                    <div class="col-lg-12">
                        <div class="db-function">
                            <a href="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'index')); ?>" class="btn btn-default btn-custom back">Trở lại</a>
                            <button type="submit" name="submit" class="btn btn-default btn-custom update">Lưu</button>
                            
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th><strong>Chức năng</strong></th>
                                        <th style="text-align: right" class="description column_descripton">Nhóm: <?php echo $arrayParam['rolename']['role_name']; ?></th>
                                    </tr>
                                    <tr>
                                        <td colspan="2" class="check-role">Tất cả <input type="checkbox" class="form-checkbox form-all"></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if($arrayParam['list']): ?>
                                        <?php foreach ($arrayParam['list'] as $key => $val): ?>
                                            <?php if(!empty(count($val['action']))):?>
                                                <tr>
                                                    <td colspan="2"><strong><?php echo $val['controller']; ?></strong></td>
                                                </tr>
                                                <?php foreach ($val['action'] as $key => $value): ?>
                                                <tr>
                                                    <td class="resource"><?php echo $value['name']; ?> <span>(<?php echo $value['description']? $value['description']: $val['module'] .'-'. $val['controller'].'-'.$value['name']; ?>)</span></td>
                                                    <td class="check-role" ><input <?php echo $value['flag']?'checked':''; ?> class="form-checkbox form-all" type="checkbox" name="permission[]" value="<?php echo $value['id']; ?>" ></td>
                                                </tr>

                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="action-footer">
                            <div class="db-function">
                                <!--<button type="submit" class="btn btn-default btn-custom update">Lưu</button>-->
                            </div>
                        </div>
                        
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    jQuery(document).ready(function($){
        
        
    });
</script>