<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Nhập tin tức</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'news', 'action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'news', 'action' => 'add')) ?>" id="form-add-user" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="box">
                                        <div class="box-header"><h2>Thông tin cơ bản</h2></div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="name">Tiêu đề</label><span class="validation">*</span>
                                                        <input type="text" data-toggle="tooltip" value="<?php echo isset($arrayParam['post']['name'])?$arrayParam['post']['name']:'' ?>" data-placement="top" title="Tiêu đề tin tức" class="form-control" id="name" name="name">
                                                        <p class="error"><?php echo isset($arrayParam['error']['name'])? $arrayParam['error']['name']:'' ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="slug">Slug</label><span class="validation">*</span>
                                                        <input type="text" data-toggle="tooltip" value="<?php echo isset($arrayParam['post']['slug'])?$arrayParam['post']['slug']:'' ?>" data-placement="top" title="Nhập alias cho tin tức" class="form-control" id="slug" name="slug">
                                                        <p class="error"><?php echo isset($arrayParam['error']['slug'])? $arrayParam['error']['slug']:'' ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                            <div class="form-group">
                                                                <label>Danh mục</label><span class="validation">*</span>
                                                                <select name="category_id" id="category_id" class="selectpicker show-tick form-control" data-live-search="true">
                                                                    <?php echo $category; ?>
                                                                </select>
                                                                <p class="error"><?php echo isset($arrayParam['error']['category_id'])? $arrayParam['error']['category_id']:'' ?></p>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                            <label>&nbsp;</label>
                                                            <div class="add-item" data-toggle="modal" data-target=".bs-category"><i class="fa fa-plus"></i></div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="startday">Ngày đăng</label>
                                                                <input type="date" id="startday" value="<?php echo (isset($arrayParam['post']['startday']) && !empty($arrayParam['post']['startday']))? date('Y-m-d',$arrayParam['post']['startday']) :'' ?>"  name="startday" class="form-control" data-toggle="tooltip" data-placement="top" title="Ngày đăng">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="endday">Ngày hạ</label>
                                                                <input type="date" id="endday" value="<?php echo (isset($arrayParam['post']['endday']) && !empty($arrayParam['post']['endday']))? date('Y-m-d', $arrayParam['post']['endday']):'' ?>" class="form-control" data-toggle="tooltip" data-placement="top" title="Ngày hạ" name="endday">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                

                                                

                                               
                                            </div>
                                        </div>
                                    </div>

                                    

                                    <div class="box">
                                        <div class="box-header"><h2><i class="fa fa-plus"></i> Thông tin website</h2></div>
                                        <div class="box-body box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="status" value="0">
                                                                        <input type="checkbox" name="status" id="promote" value="1" <?php echo (!isset($arrayParam['post']['status']))?'checked':((isset($arrayParam['post']['status'])) && $arrayParam['post']['status'] == 1)?'checked':'' ?>>
                                                                        Đăng
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="sort">Sắp xếp</label>
                                                                <input type="number" min="0" value="<?php echo isset($arrayParam['post']['sort'])?$arrayParam['post']['sort']:'0' ?>" class="form-control" id="sort" name="sort" placeholder="0" data-toggle="tooltip" data-placement="top" title='Nhập thử tự hiển thị'>
                                                            </div>
                                                        </div>
                                                        
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="box">
                                        <div class="box-header"><h2>Thư viện ảnh</h2></div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="image">Ảnh đại điện</label><span class="validation">*</span>
                                                        <input type="file" name="image" class="form-control" id="image">
                                                        <p class="error"><?php echo isset($arrayParam['error']['image'])? $arrayParam['error']['image']:'' ?></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="box">
                                        <div class="box-header"><h2><i class="fa fa-plus"></i> Thông tin SEO</h2></div>
                                        <div class="box-body box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="title">Meta title</label>
                                                        <input type="text" class="form-control" name="title" value="<?php echo isset($arrayParam['post']['title'])?$arrayParam['post']['title']:'' ?>" id="title" data-toggle="tooltip" data-placement="top" title="Nhập tiêu đề SEO">
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="keyword">Meta keyword</label>
                                                        <input type="text" name="keyword" value="<?php echo isset($arrayParam['post']['keyword'])?$arrayParam['post']['keyword']:'' ?>" class="form-control" id="keyword" data-toggle="tooltip" data-placement="top" title="Nhập từ khóa SEO">
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="description">Meta description</label>
                                                        <textarea class="form-control" rows="3" name="description" data-toggle="tooltip" data-placement="top" title="Nhập mô tả SEO"><?php echo isset($arrayParam['post']['description'])?$arrayParam['post']['description']:'' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="box">
                                        <div class="box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="except">Mô tả ngắn</label>
                                                        <textarea class="form-control ckeditor_excerpt" id="ckeditor_excerpt" rows="3" name="excerpt" data-toggle="tooltip" data-placement="top" title="Mô tả ngắn"><?php echo isset($arrayParam['post']['except'])?$arrayParam['post']['except']:'' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="box">
                                        <div class="box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="content">Nội dung</label>
                                                        <textarea class="form-control ckeditor" id="ckeditor" rows="3" name="content" data-toggle="tooltip" data-placement="top" title="Nội dung"><?php echo isset($arrayParam['post']['content'])?$arrayParam['post']['content']:'' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                    <button type="submit" name="save" value="save" class="btn btn-default btn-custom add">Lưu</button>
                                    <button type="submit" name="save-news" value="save-news" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="modal fade bs-category modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm danh mục</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="category_ajax">Tên</label>
                        <input type="text" class="form-control" id="category_name" placeholder="Tên">
                        <p class="error" id="category_name_error"></p>
                    </div>
                    <div class="form-group">
                        <label for="category_slug">Slug</label>
                        <input type="text" class="form-control" id="category_slug" placeholder="Slug">
                        <p class="error" id="category_slug_error"></p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Nhóm cha</label>
                            <div class="form-control-category">
                                <select name="parent" id="add-category" class="selectpicker show-tick form-control" data-live-search="true">
                                </select>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" id="btn-category-add" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.bs-category').on('shown.bs.modal', function () {
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'news', 'action' => 'ajaxnewsloadcategory')) ?>",
                data: {},
                dataType: 'JSON',
                beforeSend: function( xhr ) {
                     $(".form-control-category").addClass('on');
                },
                success: function(data){
                    $("#add-category").empty().append(data.data);
                    $('#add-category').selectpicker('refresh');
                    $(".form-control-category").removeClass('on');
                }    
           });
        });
        $("#btn-category-add").on('click', function(){
            var name = $("#category_name").val();
            var slug = $('#category_slug').val();
            var category = $("#add-category").val();
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'news', 'action' => 'ajaxnewsaddcategory')) ?>",
                data: {'name': name, 'slug': slug , 'parent': category},
                dataType: 'JSON',
                success: function(data){
                    console.log(data);
                    if(data.error){
                        $("#category_name_error").empty().append(data.error.name);
                        $("#category_slug_error").empty().append(data.error.slug);
                    }else{
                        $('.bs-category').modal('hide');
                        $("#category_name").val('');
                        $('#category_slug').val('');
                        $("#category_id").empty().append(data.reloadCategory);
                        $('#category_id').selectpicker('refresh');
                    }
                }    
           });
        });
    });
</script>