<?php echo $this->doctype(); ?>
<html lang="vi">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CMS '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image', 'href' => $this->basePath() . '/img/faviconaa.ico'))
						->prependStylesheet($this->basePath() . '/css/responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/libs/scrollbar/jquery.mCustomScrollbar.min.css')
						->prependStylesheet($this->basePath() . '/libs/bootstrap-select/dist/css/bootstrap-select.min.css')
						->prependStylesheet($this->basePath() . '/libs/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.form.js')
            ->prependFile($this->basePath() . '/js/scripts.js')
            ->prependFile($this->basePath() . '/libs/ckeditor/ckeditor_config.js')
            ->prependFile($this->basePath() . '/libs/ckeditor/ckeditor.js')
			->prependFile($this->basePath() . '/libs/scrollbar/jquery.mCustomScrollbar.concat.min.js')
			->prependFile($this->basePath() . '/libs/bootstrap-select/dist/js/bootstrap-select.min.js')
            ->prependFile($this->basePath() . '/libs/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.3.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <?php // $this->adminheader(); ?>
        <div class="wrapper">
<!--            <nav class="sidebar">
                    <div class="menu-top">
                        
                        <ul class="menu-nav">-->
<!--                            <li><a href="javascript:void(0)"><span class="icon dashboard"></span>Tổng quan</a>
                            </li>
                            <li class="active"> 
                                <a class="active"><span class="icon iconproduct"></span> Hệ thống <i class="fa pull-right fa-angle-right"></i></a>
                                <ul class="item">
                                    <li><a href="<?php echo $this->url('backend', array('controller' => 'language', 'action' => 'index')); ?>"><i class="fa fa-angle-right"></i> Ngôn ngữ</a></li>
                                </ul>
                            </li>
                            <li class="active"> 
                                <a class="active"><span class="icon iconproduct"></span> Phân quyền <i class="fa pull-right fa-angle-right"></i></a>
                                <ul class="item">
                                    <li><a href="<?php echo $this->url('backend', array('controller' => 'permission', 'action' => 'permission')); ?>"><i class="fa fa-angle-right"></i> Permissions</a></li>
                                    <li><a href="<?php echo $this->url('backend', array('controller' => 'role', 'action' => 'index')); ?>"><i class="fa fa-angle-right"></i> Roles</a></li>
                                    <li><a href="<?php echo $this->url('backend', array('controller' => 'resource', 'action' => 'index')); ?>"><i class="fa fa-angle-right"></i> Resources</a></li>
                                    <li><a href="<?php echo $this->url('backend', array('controller' => 'permission', 'action' => 'index')); ?>"><i class="fa fa-angle-right"></i> Privilege</a></li>
                                </ul>
                            </li>
                            <li class="active">
                                <a  href="#" class="active"><span class="icon iconstore"></span> Giao dịch <i class="fa pull-right fa-angle-right"></i></a>
                                <ul class="item">
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Hóa đơn</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Trả hàng</a></li>
                                    <li><a href="#" class="active"><i class="fa fa-angle-right"></i> Nhập hàng</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Trả hàng nhập</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Chuyển hàng</a></li>
                                </ul>
                            </li>-->
<!--                            <li>
                                <a href="#"><span class="icon iconpartner"></span> Đối tác <i class="fa pull-right fa-angle-right"></i></a>
                                <ul class="item">
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Khách hàng</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Nhà cung cấp</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Thương Hiệu</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#"><span class="icon iconinvoice"></span> Báo cáo <i class="fa pull-right fa-angle-right"></i></a>
                                <ul class="item">
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Bán hàng</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Hàng hóa</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Tài chính </a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Công nợ</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Cuối ngày</a></li>
                                </ul>
                            </li>
							
                            <li>
                                <a href="#"><span class="icon iconconfig"></span> Thiết lập <i class="fa pull-right fa-angle-right"></i></a>
                                <ul class="item">
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Quản lý thành viên</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Quản lý nhân viên</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Quản lý cửa hàng </a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Phân quyền hệ thống</a></li>
                                    <li><a href="#"><i class="fa fa-angle-right"></i> Quản lý Email</a></li>
                                </ul>
                            </li>
                            <li><a href="#"> <span class="icon iconsale"></span>Bán hàng </a></li>
                            <li><a href="#"><span class="icon iconhelp"></span> Hỗ trợ </a></li>-->
<!--                        </ul>
                        
                        
                    </div>
            </nav>-->
            <div class="main">
                <div id="messages">
                    <?php
                     $flashMessage = $this->flashMessenger()->getMessages();
                        if(!empty($flashMessage))
                        {
                            echo $flashMessage[0];
                        }
                    ?>
                </div>
                <?php echo $this->content ?>
            </div>
        </div>
        
		
        <?php echo $this->inlineScript() ?>
		<!--<div class="showcase"></div>-->
    </body>
</html>
