<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CMS '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/libs/scrollbar/jquery.mCustomScrollbar.min.css')
						->prependStylesheet($this->basePath() . '/libs/bootstrap-select/dist/css/bootstrap-select.min.css')
						->prependStylesheet($this->basePath() . '/libs/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/scripts.js')
			->prependFile($this->basePath() . '/libs/scrollbar/jquery.mCustomScrollbar.concat.min.js')
			->prependFile($this->basePath() . '/libs/bootstrap-select/dist/js/bootstrap-select.min.js')
            ->prependFile($this->basePath() . '/libs/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.3.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
		
		
        login form
        
		
        <?php echo $this->inlineScript() ?>
		<!--<div class="showcase"></div>-->
    </body>
</html>
