<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-block">
                <p class="logo"><a href="#"><img src="<?php echo $this->basePath('img/logo.png'); ?>"></a></p>
                <p class="address"><strong>Address: </strong>25 Le Lai, Phuong 25, Quan Tan Binh, HCMC</p>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">News</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
                <p class="coppyright">Coppyright 2015 <span>chance4all.net </span>all rights reserved</p>
            </div>
            <div class="col-md-4">
                <div class="news">
                    <h2>News</h2>
                    <ul>
                        <li><a href="#">Sed do eiusmod tempor incididunt ut labore et dolore</a></li>
                        <li><a href="#">Officia deserunt mollit anim id est laborum.</a></li>
                        <li><a href="#">Laboris nisi ut aliquip ex ea commodo consequat. </a></li>
                        <li><a href="#">Esse cillum dolore eu fugiat nulla pariatur</a></li>
                        <li><a href="#">Ullamco laboris nisi ut aliquip ex ea commodo consequat.</a></li>
                    </ul>
                    <p>
                        <a href="#" class="readmove">Read move  <i class="fa fa-angle-double-right"></i></a>
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                    </ul>
                </div>
                <div class="phone-email">
                    <ul>
                        <li><a href="#"><i class="fa fa-envelope-o"></i> vanlong200880@gmail.com</a></li>
                        <li><a href="#"><i class="fa fa-mobile"></i> 09 6666 0127</a></li>
                    </ul>
                </div>
                <div class="support">
                    <ul>
                        <li><a href="#"><i class="fa fa-skype"></i> vanlong200880</a></li>
                        <li><a href="#"><i class="fa fa-skype"></i> vanlong200880</a></li>
                        <li><a href="#"><i class="fa fa-skype"></i> vanlong200880</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>