<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-block animated fadeInUp">
                <p class="logo"><a href="#"><img src="<?php echo $this->basePath('img/logo.png'); ?>"></a></p>
                <p class="address"><strong>Address: </strong>25 Le Lai, Phuong 25, Quan Tan Binh, HCMC</p>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">News</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
                <p class="coppyright">Coppyright 2015 <span>chance4all.net </span>all rights reserved</p>
            </div>
            <div class="col-md-4 animated fadeInUp">
                <div class="news">
                    <h2>News</h2>
                    <ul>
                        <li><a href="#">Sed do eiusmod tempor incididunt ut labore et dolore</a></li>
                        <li><a href="#">Officia deserunt mollit anim id est laborum.</a></li>
                        <li><a href="#">Laboris nisi ut aliquip ex ea commodo consequat. </a></li>
                        <li><a href="#">Esse cillum dolore eu fugiat nulla pariatur</a></li>
                        <li><a href="#">Ullamco laboris nisi ut aliquip ex ea commodo consequat.</a></li>
                    </ul>
                    <p>
                        <a href="#" class="readmove">Read move  <i class="fa fa-angle-double-right"></i></a>
                    </p>
                </div>
            </div>
            <div class="col-md-4 animated fadeInUp">
                <div class="social">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter-square"></i></a></li>
                    </ul>
                </div>
                <div class="phone-email">
                    <ul>
                        <li><a href="#"><i class="fa fa-envelope-o"></i> vanlong200880@gmail.com</a></li>
                        <li><a href="#"><i class="fa fa-mobile"></i> 09 6666 0127</a></li>
                    </ul>
                </div>
                <div class="support">
                    <ul>
                        <li><a href="#"><i class="fa fa-skype"></i> vanlong200880</a></li>
                        <li><a href="#"><i class="fa fa-skype"></i> vanlong200880</a></li>
                        <li><a href="#"><i class="fa fa-skype"></i> vanlong200880</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

<div id="login" class="modal fade bs-example-modal-sm deposit-form" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Sign In</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <input type="text" class="form-control" id="username" value="" placeholder="Username">
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input type="password" class="form-control" id="password" value="" placeholder="Password">
                    </div>
                </div>
                <div class="form-group">
                    <button type="button" class="btn btn-primary">Login</button>
                    <a href="#" class="forgot-password control-label">Forgot password?</a>
                </div>
                <div class="login-line"></div>
                <p>Don't have an account <a href="#" id="sign-up-here">Sign Up Here</a></p>
            </div>
        </div>
      </div>
    </div>
    
    <!-- Button trigger modal -->


    <!-- forgot password -->
    <div id="forgot" class="modal fade deposit-form" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Forgot password?</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <input type="text" class="form-control" id="email" value="" placeholder="Email">
                    </div>
                </div>
                <button type="button" class="btn btn-primary">Forgot password</button>
            </div>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade deposit-form" id="register" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Register User</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="sponsor-id" class="col-sm-4 control-label">Sponsor ID:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="sponsor-id" id="sponsor-id">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="commitment-amount" class="col-sm-4 control-label">Commitment Amount:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <select class="form-control">
                                    <option value="1">Select commitment</option>
                                    <option value="2">Option 1</option>
                                    <option value="3">Option 2</option>
                                    <option value="3">Option 3</option>
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="member-name" class="col-sm-4 control-label">Member Name:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="member-name" id="member-name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="mobile" class="col-sm-4 control-label">Mobile No.:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <select class="form-control">
                                            <option value="1">+015</option>
                                            <option value="2">+84</option>
                                            <option value="3">+87</option>
                                            <option value="3">+064</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" name="mobile" id="mobile">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-sm-4 control-label">Email:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="email" id="email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-sm-4 control-label">Country:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <select class="form-control">
                                    <option value="1">Select Country</option>
                                    <option value="2">Vietnam</option>
                                    <option value="3">Japan</option>
                                    <option value="3">My</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="skype" class="col-sm-4 control-label">Skype:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="skype" id="skype">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="security" class="col-sm-4 control-label">Security code:<span class="validation">*</span> </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" name="security" id="security">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="security" class="col-sm-4 control-label"></label>
                            <div class="col-sm-8">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <button type="button" class="btn btn-primary">Register</button>
                                    </div>
                                    <div class="col-sm-9">
                                        <p>you already have an account? <a href="#" id="login-here">Login</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
<script>
    jQuery(document).ready(function($){
        var heightHeader        = $(".header").height();
        var sliderHeight        = $("#slider").height();
        var blockDepositHeight  = $(".block-deposit").height();
        var blockAboutUsHeight  = $(".block-about-us").height();
        var statisticsHeight    = $(".statistics").height();
        var footerHeight        = $(".footer").height();
        var wrapperHeight       = $(".wrapper").height();
        var paymentHeight       = $(".payment").height();
        $(window).scroll(function(){
            var ScrollTop = parseInt($(window).scrollTop());
            if (ScrollTop > (heightHeader+sliderHeight/10-100)) {
                $("div.item-blance ul li").css("display", "block");
            }
            if (ScrollTop > (heightHeader+sliderHeight+blockDepositHeight/15)) {
                $(".block-about-us .animated").css("display", "block");
            }
            if (ScrollTop > (heightHeader+sliderHeight+blockDepositHeight +statisticsHeight/2 - 300)) {
                $(".statistics ul.animated").css("display", "block");
            }
            if (ScrollTop > (heightHeader+ wrapperHeight/2 + paymentHeight)) {
                $(".payment .animated").css("display", "block");
            }
            if (ScrollTop > (heightHeader+ wrapperHeight/2 + paymentHeight + footerHeight)) {
                $(".footer .animated").css("display", "block");
            }
        });

        // user login 
        $("#sign-up-here").on('click', function(){
            $(".close").trigger('click');
            setTimeout(function(){ 
                 $("#register").modal('show'); 
             }, 500);
        });
        $("#login-here").on('click', function(){
            $(".close").trigger('click');
            setTimeout(function(){ 
                 $("#login").modal('show'); 
             }, 500);
        });
        $(".forgot-password.control-label").on('click', function(){
            $(".close").trigger('click');
            setTimeout(function(){ 
                 $("#forgot").modal('show'); 
             }, 500);
        });
    });
</script>