<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Ngôn ngữ</h1>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <select class="form-control selected-custom">
                        <option value="">Chọn</option>
                        <option value="delete">Xóa vĩnh viễn</option>
                        <option value="delete_flag">Xóa tạm thời</option>
                        <option value="published">Đăng</option>
                        <option value="unpublished">Tạm dừng</option>
                        <option value="update_weight">Cập nhật vị trí</option>
                    </select>
                    <button type="button" class="btn btn-default btn-custom apply">Thực hiện</button>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><button type="button" class="btn btn-default btn-custom pull-right">Thêm mới</button></div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filter"> 
                            <form class="form-horizontal">
                                <fieldset>
                                    <legend>Tìm kiếm</legend>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Từ khóa</label>
                                            <div class="col-lg-9 col-md-8 col-sm-12">
                                                <input type="email" class="form-control" id="keyword">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button type="button" class="btn btn-default btn-custom">Tìm</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div> <!-- end search -->

                    <div class="col-lg-12">
                        <div class="form-table">
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                        <th id="key" class="name column_name no-sort">
                                            <a href="#">Mã <i class="fa fa-sort-asc"></i></a>
                                        </th>
                                        <th id="name">
                                            <a class="desc" href="#">Tên <i class="fa fa-sort-desc"></i></a>
                                        </th>
                                        <th class="description column_descripton">Code</th>
                                        <th class="description column_descripton">Icon</th>
                                        <th class="description column_descripton">Mặc định</th>
                                        <th class="status column_status">Trang thái</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>1</td>
                                        <td class="column-title column_name">
                                            <strong class="key-title">Tiếng Việt</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 1" data-slug="ten-1" data-weight="1" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">vi</td>
                                        <td class="column_quantity"> <img src="<?php echo $this->basePath('language/vi.png');?>"></td>
                                        <td class="column_descripton"></td>
                                        <td class="column_status status"><a title="Hiển thị" class="fa fa-check-circle"></a></td>
                                    </tr>

                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>2</td>
                                        <td class="column-title column_name">
                                            <strong>English</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 2" data-slug="ten-2" data-weight="2" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">en</td>
                                        <td class="column_quantity"><img src="<?php echo $this->basePath('language/en.png');?>"></td>
                                         <td class="column_descripton">Default</td>
                                        <td class="column_status unstatus"><a title="Không hiển thị" class="fa fa-minus-circle"></a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="pager">
                <ul class="pagination">
                    <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="#" title="Lùi lại"><i class="fa fa-angle-left"></i></a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li class="active"><a>3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#" title="Tiếp theo"><i class="fa fa-angle-right"></i></a></li>
                    <li><a href="#" title="Trang Cuối"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>

            </div>
        </div>
    </div>
</div>