<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Language</h1>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <select class="form-control selected-custom">
                        <option value="">Choose</option>
                        <option value="delete">Delete</option>
                        <option value="delete_flag">Delete forever</option>
                        <option value="published">Published</option>
                        <option value="unpublished">Unpublished</option>
                    </select>
                    <button type="button" class="btn btn-default btn-custom apply">Apply</button>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><a href="<?php echo $this->url('backend', array('controller' => 'language','action' => 'add')) ?>" class="btn btn-default btn-custom pull-right">Add language</a></div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filter"> 
                            <form class="form-horizontal">
                                <fieldset>
                                    <legend>Search</legend>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Keyword</label>
                                            <div class="col-lg-9 col-md-8 col-sm-12">
                                                <input type="email" class="form-control" id="keyword">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button type="button" class="btn btn-default btn-custom">Submit</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div> <!-- end search -->

                    <div class="col-lg-12">
                        <div class="form-table">
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                        <th id="key" class="name column_name no-sort">
                                            <a href="#">Id <i class="fa fa-sort-asc"></i></a>
                                        </th>
                                        <th id="name">
                                            <a class="desc" href="#">Name <i class="fa fa-sort-desc"></i></a>
                                        </th>
                                        <th class="description column_descripton">Code</th>
                                        <th class="description column_descripton">Icon</th>
                                        <th class="description column_descripton">Default</th>
                                        <th class="status column_status">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>1</td>
                                        <td class="column-title column_name">
                                            <strong class="key-title">Tiếng Việt</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Edit</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tiếng Việt" data-code="vi" data-weight="1" href="javascript:void(0)">Quick Edit</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Delete</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">View</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">vi</td>
                                        <td class="column_quantity"> <img src="<?php echo $this->basePath('language/vi.png');?>"></td>
                                        <td class="column_descripton"></td>
                                        <td class="column_status status"><a title="Hiển thị" class="fa fa-check-circle"></a></td>
                                    </tr>

                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>2</td>
                                        <td class="column-title column_name">
                                            <strong>English</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Edit</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="English" data-code="en" data-weight="2" href="javascript:void(0)">Quick Edit</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Delete</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">View</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">en</td>
                                        <td class="column_quantity"><img src="<?php echo $this->basePath('language/en.png');?>"></td>
                                        <td class="column_descripton"><a href="#">Default</a></td>
                                        <td class="column_status unstatus"><a title="Không hiển thị" class="fa fa-minus-circle"></a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.form-table .table>tbody>tr>td span.quick-edit a').on('click', function(){
            $(".form-table .table>tbody>tr").removeAttr('style');
            $(this).closest('tr').css('display', 'none');
            $('.edit-row').remove();
            var name = $(this).attr('data-name');
            var slug = $(this).attr('data-code');
            var weight = $(this).attr('data-weight');
            var html = '';
            html +='<tr id="edit-1" class="edit-row">';
            html +='    <td colspan="7" class="">';
            html +='        <div class="column-qiuck-edit">';
            html +='            <div class="col-lg-12"><h2>Quick Edit</h2></div>';
            html +='            <div class="col-lg-12">';
            html +='                <div class="row">';
            html +='                    <div class="col-lg-6">';
            html +='                        <div class="form-group">';
            html +='                            <label for="name">Name</label>';
            html +='                            <input type="text" class="form-control" value="'+name+'" id="name">';
            html +='                        </div>';
            html +='                        <div class="form-group">';
            html +='                            <label for="name">Code</label>';
            html +='                            <input type="text" class="form-control" value="'+slug+'" id="slug">';
            html +='                        </div>';
            html +='                    </div>';
            html +='                </div>';
            html +='            </div>';
            html +='            <div class="col-lg-12">';
            html +='                <div class="row">';
            html +='                    <div class="col-lg-6">';
            html +='                        <div class="form-group">';
            html +='                            <button type="button" class="btn btn-default btn-back">Back</button>';
            html +='                            <button type="button" class="btn btn-default btn-custom pull-right">Update</button>';
            html +='                        </div>';
            html +='                    </div>';
            html +='                </div>';
            html +='            </div>';
            html +='            <div class="col-lg-6"></div>';
            html +='        </div>';
            html +='    </td>';
            html +='</tr>';
            $(this).closest('tr').after(html);
       });

       $('.form-table').on('click', '.table>tbody>tr .btn-back', function(){
            $(".form-table .table>tbody>tr").removeAttr('style');
            $('.edit-row').remove();
       });
    });
</script>