<?php 
	$this->headTitle($about['title']);
	$this->headMeta()->appendName('keywords', $about['keyword']);
	$this->headMeta()->appendName('description', $about['description']);
?>
<section class="about">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a> <i class="fa fa-angle-double-right"></i></li>
				  <li class="active"><?php echo $about['name']; ?></li>
				 
				</ol>
			</div>
      
      <div class="col-md-8">
        <?php echo $about['content']; ?>
      </div>
      <div class="col-md-4">
        <?php echo $this->newsrelated(); ?>
      </div>
    </div>
  </div>
</section>