<header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row header">
                            <div class="col-lg-4 col-xs-4">
                                <div class="logo">
                                    <a href="#">Logo</a>
                                </div>
                                <div class="menu-sliderbar"><i class="fa fa-bars"></i></div>
                            </div>
                            <div class="col-lg-8 col-xs-8 profile">
                                <div class="user pull-right">
                                    <ul id="user-profile" class="nav navbar-nav">
                                        <li class="dropdown user user-menu">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <span class="icon-profile">
                                                    <img src="<?php echo $this->basePath('default/avatar.png');?>">
                                                </span>
                                                <span><?php echo $data['userFullName']; ?> <i class="caret"></i></span>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li class="user-header bg-light-blue">
                                                    <?php if(empty($data['userAvartar']) || $data['userAvartar'] ==''): ?>
                                                    <img src="<?php echo $this->basePath('default/avatar.png');?>" class="img-circle">
                                                    <?php else: ?>
                                                    <img src="<?php echo $this->basePath(USER_AVARTAR .'/'.$data['userAvartar']);?>" class="img-circle">
                                                    <?php endif; ?>
                                                    <p>
                                                        <?php echo $data['userFullName']; ?> 
                                                        - <?php echo $data['userRole']; ?> 
                                                        <small>đăng ký ngày <?php echo date('d/m/Y',$data['userCreated']); ?></small>
                                                    </p>
                                                </li>

                                                <li class="user-footer">
                                                    <div class="pull-left">
                                                        <a href="/profile" class="btn-profile">Profile</a>
                                                    </div>
                                                    <div class="pull-right">
                                                        <a href="<?php echo $this->url('backend', array('controller' => 'public', 'action' => 'logout')) ?>" class="btn-profile logout">Sign out</a>
                                                    </div>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</header>