<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm nhà cung cấp</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
					<a href="<?php echo $this->url('backend', array('controller' => 'supplier', 'action' => 'inex')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'supplier', 'action' => 'edit', 'id' => $arrayParam['id'])); ?>" method="post" enctype="multipart/form-data">
	<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin chung</h2></div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="name">Tên nhà cung cấp <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Nhập tên nhà cung cấp">?</span></label>
                                                    <input type="text" class="form-control" value="<?php echo isset($arrayParam['post']['name'])?$arrayParam['post']['name']:'' ?>" id="post-name" name="name">
																										<p class="error"><?php echo isset($arrayParam['error']['name'])? $arrayParam['error']['name']:'' ?></p>
                                                </div>
                                            </div>
																					
																						<div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="slug">Slug <span class="help" data-toggle="tooltip" data-placement="right" title="Nhập tên nhà cung cấp">?</span></label>
                                                    <input type="text" class="form-control" id="post-alias" value="<?php echo isset($arrayParam['post']['slug'])?$arrayParam['post']['slug']:'' ?>" name="slug">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin thêm</h2></div>
                                    <div class="box-body">
                                        <div class="row">
																						<div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="phone">Điện thoại  <span class="help" data-toggle="tooltip" data-placement="right" title='Nhập số điện thoại'>?</span></label>
                                                            <input type="phone" class="form-control" name="phone" value="<?php echo isset($arrayParam['post']['phone'])?$arrayParam['post']['phone']:'' ?>" id="phone">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <label for="email">Email <span class="help" data-toggle="tooltip" data-placement="right" title='Đây là trường không bắt buộc.'>?</span></label>
                                                    <input type="email" class="form-control" id="email" value="<?php echo isset($arrayParam['post']['email'])?$arrayParam['post']['email']:'' ?>" name="email">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="address">Địa chỉ <span class="help" data-toggle="tooltip" data-placement="right" title='Đây là trường không bắt buộc.'>?</span></label>
                                                    <input type="text" class="form-control" id="address" value="<?php echo isset($arrayParam['post']['address'])?$arrayParam['post']['address']:'' ?>" name="address">
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="companyname">Công ty ( doanh nghiệp ) <span class="help" data-toggle="tooltip" data-placement="right" title='Đây là trường không bắt buộc.'>?</span></label>
                                                    <input type="text" class="form-control" id="companyname" name="companyname" value="<?php echo isset($arrayParam['post']['companyname'])?$arrayParam['post']['companyname']:'' ?>">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="tax">Mã số thuế <span class="help" data-toggle="tooltip" data-placement="right" title='Đây là trường không bắt buộc.'>?</span></label>
                                                            <input type="text" class="form-control" value="<?php echo isset($arrayParam['post']['tax'])?$arrayParam['post']['tax']:'' ?>" name="tax" id="tax">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
																					<div class="col-lg-12">
																						<div class="row">
																							<div class="col-lg-6">
																									<div class="form-group">
																											<label for="account">Tài khoản <span class="help" data-toggle="tooltip" data-placement="right" title='Đây là trường không bắt buộc.'>?</span></label>
																											<input type="text" class="form-control" id="account" value="<?php echo isset($arrayParam['post']['account'])?$arrayParam['post']['account']:'' ?>" name="account">
																									</div>
																							</div>
																						</div>
																					</div>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
															<div class="box">
																<div class="box-header"><h2>Thông tin chung</h2></div>
																<div class="box-body">
																		<div class="row">
																				<div class="col-lg-6">
																					<div class="form-group">
																							<div class="checkbox">
																									<label>
																											<input type="hidden" name="status" value="0">
																											<input type="checkbox" name="status" id="promote" value="1" <?php echo (!isset($arrayParam['post']['status']))?'checked':((isset($arrayParam['post']['status'])) && $arrayParam['post']['status'] == 1)?'checked':'' ?>>
																											Đăng
																									</label>
																							</div>
																					</div>
																			</div>

																				<div class="col-lg-12">
																						<div class="form-group">
																								<label for="order">Sắp xếp <span class="help" data-toggle="tooltip" data-placement="right" title="Sắp xếp">?</span></label>
																								<input type="number" min="0" class="form-control" id="order" value="<?php echo isset($arrayParam['post']['order'])?$arrayParam['post']['order']:'' ?>" name="order">
																						</div>
																				</div>
																				<div class="col-lg-12">
																						<div class="row">
																								<div class="col-lg-12">
																										<div class="form-group">
																												<label for="weight">Ghi chú <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
																												<textarea class="form-control" rows="3" name="note" placeholder="Ghi chú" ><?php echo isset($arrayParam['post']['note'])?$arrayParam['post']['note']:'' ?></textarea>
																										</div>
																								</div>
																						</div>
																				</div>
																		</div>
																</div>
														</div>

                                <div class="box box-botton">
                                    <div class="box-footer">
																			<a href="<?php echo $this->url('backend', array('controller' => 'supplier', 'action' => 'index')); ?>" class="btn btn-default btn-back add">Nhập lại</a>
																			<button type="submit" name="save" value="save" class="btn btn-default btn-custom add">Cập nhật</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>
