<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm sản phẩm</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <button type="button" class="btn btn-default btn-custom pull-right">Trở lại</button>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin chung</h2></div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="name">Tên</label>
                                                <input type="text" class="form-control" id="name" placeholder="Tên">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="slug">Slug</label>
                                                <input type="text" class="form-control" id="slug" placeholder="Slug">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                    <div class="form-group">
                                                        <label for="quantity">Danh mục</label>
                                                        <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                            <option>cow</option>
                                                            <option>bull</option>
                                                            <option class="get-class" disabled>ox</option>
                                                            <optgroup label="test" data-subtext="another test">
                                                                <option>ASD</option>
                                                                <option selected>Bla</option>
                                                                <option>Ble</option>
                                                            </optgroup>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                    <label for="quantity">&nbsp;</label>
                                                    <div class="add-item"><i class="fa fa-plus"></i></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="price">Giá nhập</label>
                                                <input type="text" class="form-control" id="price" placeholder="Giá nhập">
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="price_cost">Giá bán</label>
                                                <input type="text" class="form-control" id="price_cost" placeholder="Giá bán">
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label for="quantity">Số lượng</label>
                                                        <input type="number" class="form-control" id="quantity" placeholder="Tồn kho">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                    <div class="form-group">
                                                        <label for="quantity">Chọn kho hàng</label>
                                                        <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                            <option>cow</option>
                                                            <option>bull</option>
                                                            <option class="get-class" disabled>ox</option>
                                                            <optgroup label="test" data-subtext="another test">
                                                                <option>ASD</option>
                                                                <option selected>Bla</option>
                                                                <option>Ble</option>
                                                            </optgroup>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                    <label for="quantity">&nbsp;</label>
                                                    <div class="add-item"><i class="fa fa-plus"></i></div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                    <div class="form-group">
                                                        <label for="quantity">Thương hiệu</label>
                                                        <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                            <option>cow</option>
                                                            <option>bull</option>
                                                            <option class="get-class" disabled>ox</option>
                                                            <optgroup label="test" data-subtext="another test">
                                                                <option>ASD</option>
                                                                <option selected>Bla</option>
                                                                <option>Ble</option>
                                                            </optgroup>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                    <label for="quantity">&nbsp;</label>
                                                    <div class="add-item"><i class="fa fa-plus"></i></div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        
                                    </div>
                                </div>
                                
                                
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin thêm</h2></div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="color">Màu sắc</label>
                                                <input type="text" class="form-control" id="color" placeholder="Color">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="name">Size</label>
                                                <input type="text" class="form-control" id="size" placeholder="Size">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label for="weight">Vị trí</label>
                                                        <input type="number" class="form-control" id="weight" placeholder="Vị trí">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <label for="gram">Khối lượng</label>
                                                        <input type="number" class="form-control" id="gramm" placeholder="gram">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="col-lg-12">
                                            <div class="row">
                                                <div class="col-lg-6">
                                                    <div class="form-group">
                                                        <div class="checkbox">
                                                            <label>
                                                                <input type="checkbox" name="status"> Trạng thái
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Thư viện ảnh</h2></div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="image">Ảnh đại điện</label>
                                                <input type="file" class="form-control" id="image">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="image_gallery">Ảnh gallery</label>
                                                <input type="file" class="form-control" id="image_gallery">
                                            </div>
                                        </div>
                                        
                                    </div>
                                    
                                </div>
                                <div class="box">
                                    <div class="box-header"><h2>Cài đặt SEO</h2></div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="title">Tiêu đề</label>
                                                <input type="text" class="form-control" id="title" placeholder="Tiêu đề">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="keyword">Từ khóa</label>
                                                <input type="text" class="form-control" id="keyword" placeholder="keyword">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <label for="description">Mô tả</label>
                                                <textarea class="form-control" rows="3" name="description"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="box-footer">
                                        <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
