<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>HOME</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php 
		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image', 'href' => $this->basePath() . '/img/faviconaa.ico'))
					->prependStylesheet($this->basePath() . '/css/main.css')
					->prependStylesheet($this->basePath() . '/css/bootstrap.css'); 
	?>
</head>
<body>
	<header class="header">
		<div class="container">
			<div class="row">
                <div class="col-md-12">
                    <?php echo $this->header(); ?>
                </div>
			</div>
		</div>
	</header>
	<div class="wrapper">
        <section class="section">
            <?php echo $this->content; ?>
        </section>
	</div>
	<footer class="footer">
		<div class="container">
			<div class="row">
                <div class="col-md-12">
                    <?php echo $this->header(); ?>
                </div>
			</div>
		</div>
	</footer>
</body>
</html>
