<?php
//	$param = array('controller' => $this->arrayParam['__CONTROLLER__'],'action'=>$this->arrayParam['action']);
	if(isset($this->arrayParam['id']) == true && $this->arrayParam['id'] > 0){
		$param['id'] = $this->arrayParam['id'];
	}
	$url = $this->url($this->route, array('controller' => $controller,'action' => $action));
	if($this->first != $this->current && $this->first > 0){		
		$strPageStart = '<li><a href="' . $url . '/page/1'.$routeParam.'" title="Trang đầu"><i class="fa fa-angle-double-left"></i></a></li>';
	}else{
		$strPageStart = '';
	}
	
	if(isset($this->previous)){
		$linkPrevious 	='<li><a href="' . $url . '/page/' . $this->previous . ''.$routeParam.'" title="Lùi lại"><i class="fa fa-angle-left"></i></a></li>';
	}else{
		$linkPrevious 	='';
	}
	
	if(isset($this->next)){
		$linkNext 		=' <li><a href="' . $url . '/page/' . $this->next . ''.$routeParam.'" title="Trang kế"><i class="fa fa-angle-right"></i></a></li>';
	}else{
		$linkNext 		='';
	}
	
	
	if($this->last != $this->current && $this->last > 0){
		$strPageEnd = '<li><a href="' . $url . '/page/' . $this->pageCount . ''.$routeParam.'" title="Trang cuối"><i class="fa fa-angle-double-right"></i></a></li>';
	}else{
		$strPageEnd = '';
	}
	
	$strPage  = '';
	foreach ($this->pagesInRange as $key){
		if($this->current != $key){
			$strPage .= '<li><a href="' . $url . '/page/' . $key . ''.$routeParam.'">' . $key . '</a></li>';
		}else{
			$strPage .= '<li class="active"><a href="javascript:void(0)">' . $key . '</a></li>';
		}
	}
	$page = $strPageStart . $linkPrevious . $strPage . $linkNext . $strPageEnd;
?>
<?php if($this->last > 1){?>
<div class="pager">
	<ul class="pagination">
		<?php echo $page;?>                   
	</ul>
</div>
<?php }?>             