<section class="section-breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
				  	<li>Investment Plan</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<section class="investment">
	<div class="container">
		<div class="row">
			<div class="col-md-12 investment-description">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, magni, enim. Debitis rerum accusamus magni eum, enim dignissimos minima, sed non consequatur molestias eligendi eius aliquid minus, facere officia alias. Vero possimus assumenda, soluta ipsam, veritatis animi tenetur suscipit accusamus eaque, illum quae cum reprehenderit iste recusandae laboriosam quas et, enim? Accusamus dolore esse tempora, ratione quae consequuntur voluptate obcaecati repellat qui impedit quam fugiat quia perspiciatis hic voluptatibus culpa aut inventore corrupti perferendis distinctio eum dicta nam sequi dolorum. Iste similique sit, reiciendis veritatis autem assumenda tempore, dignissimos ipsa laboriosam rem doloremque itaque ullam, aperiam repellendus, soluta at libero.</p>
        		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod temporibus odio, veritatis quibusdam deserunt alias nesciunt suscipit totam, quis, hic porro eaque excepturi cupiditate distinctio ratione dicta? Laborum ullam rerum odit facilis fugiat quaerat, nulla, deleniti reiciendis consectetur ut, id temporibus veniam odio! Sequi, quibusdam sapiente cumque, deleniti soluta facere!</p>
			</div>
			<div class="col-md-12">
				<ul class="row investment-list">
					<li class="col-md-6">
						<div class="item-investment">
							<div class="plan plan-title">
								<div class="checkbox">
									<input type='radio' name='package' value='valuable' id="package-1"/><label for="package-1"></label> 
								</div>
								<div class="period">
									<h2>Basic Plan</h2>
									<p>01% after 1 day</p>
								</div>
								<div class="percentage"><span>10%</span></div>
							</div>
							<div class="plan plan-content">
								<p>This plan was engineered with one principle in mind : Maintain the gold point between profitability & stability.</p>
								<ul class="plan-list">
									<li>
										Plan Terms
										<span class="pull-right">5.0% Daily for 30 Calendar Days</span>
									</li>
									<li>
										Plan Conditions
										<span class="pull-right">Principal Including Profits</span>
									</li>
									<li>
										Total Monthly Profits
										<span class="pull-right">150% Gross Return</span>
									</li>
									<li>
										Min - Max Deposit
										<span class="pull-right">$10 - $999</span>
									</li>
									<li>
										Min - Max Per Withdrawal
										<span class="pull-right">$1 - No Limit</span>
									</li>
									<li>
										Compound (Re-invest)
										<span class="pull-right">No Limit (Unlimited)</span>
									</li>
								</ul>
							</div>
						</div>
					</li>
          
          <li class="col-md-6">
						<div class="item-investment">
							<div class="plan plan-title">
								<div class="checkbox">
									<input type='radio' name='package' value='valuable' id="package-2"/><label for="package-2"></label> 
								</div>
								<div class="period">
									<h2>Basic Plan</h2>
									<p>01% after 1 day</p>
								</div>
								<div class="percentage"><span>10%</span></div>
							</div>
							<div class="plan plan-content">
								<p>This plan was engineered with one principle in mind : Maintain the gold point between profitability & stability.</p>
								<ul class="plan-list">
									<li>
										Plan Terms
										<span class="pull-right">5.0% Daily for 30 Calendar Days</span>
									</li>
									<li>
										Plan Conditions
										<span class="pull-right">Principal Including Profits</span>
									</li>
									<li>
										Total Monthly Profits
										<span class="pull-right">150% Gross Return</span>
									</li>
									<li>
										Min - Max Deposit
										<span class="pull-right">$10 - $999</span>
									</li>
									<li>
										Min - Max Per Withdrawal
										<span class="pull-right">$1 - No Limit</span>
									</li>
									<li>
										Compound (Re-invest)
										<span class="pull-right">No Limit (Unlimited)</span>
									</li>
								</ul>
							</div>
						</div>
					</li>
          
          <li class="col-md-6">
						<div class="item-investment">
							<div class="plan plan-title">
								<div class="checkbox">
									<input type='radio' name='package' value='valuable' id="package-3"/><label for="package-3"></label> 
								</div>
								<div class="period">
									<h2>Basic Plan</h2>
									<p>01% after 1 day</p>
								</div>
								<div class="percentage"><span>10%</span></div>
							</div>
							<div class="plan plan-content">
								<p>This plan was engineered with one principle in mind : Maintain the gold point between profitability & stability.</p>
								<ul class="plan-list">
									<li>
										Plan Terms
										<span class="pull-right">5.0% Daily for 30 Calendar Days</span>
									</li>
									<li>
										Plan Conditions
										<span class="pull-right">Principal Including Profits</span>
									</li>
									<li>
										Total Monthly Profits
										<span class="pull-right">150% Gross Return</span>
									</li>
									<li>
										Min - Max Deposit
										<span class="pull-right">$10 - $999</span>
									</li>
									<li>
										Min - Max Per Withdrawal
										<span class="pull-right">$1 - No Limit</span>
									</li>
									<li>
										Compound (Re-invest)
										<span class="pull-right">No Limit (Unlimited)</span>
									</li>
								</ul>
							</div>
						</div>
					</li>
          
          <li class="col-md-6">
						<div class="item-investment">
							<div class="plan plan-title">
								<div class="checkbox">
									<input type='radio' name='package' value='valuable' id="package-4"/><label for="package-4"></label> 
								</div>
								<div class="period">
									<h2>Basic Plan</h2>
									<p>01% after 1 day</p>
								</div>
								<div class="percentage"><span>10%</span></div>
							</div>
							<div class="plan plan-content">
								<p>This plan was engineered with one principle in mind : Maintain the gold point between profitability & stability.</p>
								<ul class="plan-list">
									<li>
										Plan Terms
										<span class="pull-right">5.0% Daily for 30 Calendar Days</span>
									</li>
									<li>
										Plan Conditions
										<span class="pull-right">Principal Including Profits</span>
									</li>
									<li>
										Total Monthly Profits
										<span class="pull-right">150% Gross Return</span>
									</li>
									<li>
										Min - Max Deposit
										<span class="pull-right">$10 - $999</span>
									</li>
									<li>
										Min - Max Per Withdrawal
										<span class="pull-right">$1 - No Limit</span>
									</li>
									<li>
										Compound (Re-invest)
										<span class="pull-right">No Limit (Unlimited)</span>
									</li>
								</ul>
							</div>
						</div>
					</li>
          
					
				</ul>
			</div>
			<div class="col-md-12">
				<div class="box calculator">
					<ul class="row payment-amount">
						<li class="col-md-3 amount">
							<div>
								<p class="amount-title">Deposit Amount (USD)</p>
                
                <div class="form-group">
                  <div class="input-group">
                    <input type="text" name="amount" class="form-control" min="1" id="amount">
                    <div class="input-group-addon">USD</div>
                  </div>
                </div>
							</div>
						</li>
						<li class="col-md-3 amount">
							<div>
								<p class="amount-title">Interest</p>
                <p class="amount-interest">0%</p>
							</div>
						</li>
						<li class="col-md-3 amount">
							<div>
								<p class="amount-title">Total</p>
                <p class="amount-total">$0.00</p>
							</div>
						</li>
            <li class="col-md-3 amount">
							<div>
                <button class="btn btn-primary">Make a Deposit Now</button>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>