<section class="user-profile confirm-deposit">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->menuuser(); ?>
			</div>
      <div class="col-md-12">
        <div class="content-user-profile">
          <div class="row">
            <div class="col-md-12">
              <ol class="breadcrumb">
                <li><a href="#">Home</a> <i class="fa fa-angle-double-right"></i></li>
                <li><a href="#">Investment plan</a> <i class="fa fa-angle-double-right"></i></li>
                <li class="active">Confirm deposit</li>

              </ol>
            </div>
            <!--<div class="col-md-12"><h1>Confirm Deposit</h1></div>-->
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-12">
                  <fieldset class="choose-plan">
                    <legend>Confirm Deposit</legend>
                    <ul class="row list-comfirm">
						<h5>Confirm deposit amount below</h5>
						
						<li>
						  Deposit amount
						  <span class="pull-right">$10.000</span>
						</li>
						<li>
						  Investment Plan
						  <span class="pull-right">5% daily for 30 calendar days</span>
						</li>
						<li>
						  Payment System
						  <span class="pull-right icon-current">
							  <img src="default/perfectmoney_icon.png" alt="perfectmoney">
						  </span>
						</li>
                    </ul>
					<div class="text-center wrap-button-confirm">
						<input class="btn-confirm" type="submit" value="Cancel">
						<input class="btn-confirm" type="submit" value="Process deposit">
					</div>
                  </fieldset>
                </div>
              </div>
            </div>            
          
          </div>
        </div>
      </div>
    </div>
  </div>
</section>