<section class="user-profile make-deposit">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->menuuser(); ?>
			</div>
      <div class="col-md-12">
        <div class="content-user-profile">
          <div class="row">
            <div class="col-md-12">
              <ol class="breadcrumb">
                <li><a href="#">Home</a> <i class="fa fa-angle-double-right"></i></li>
                <li><a href="#">User profile</a> <i class="fa fa-angle-double-right"></i></li>
                <li class="active">Make deposit</li>

              </ol>
            </div>
            <div class="col-md-12"><h1>MAKE A DEPOSIT</h1></div>
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-12">
                  <fieldset class="choose-plan">
                    <legend>CHOOSE A PLAN</legend>
                    <ul class="row list-deposit">
                      <li class="col-md-6">Basic Plan</li>
                      <li class="col-md-6">Silver Plan</li>
                      <li class="col-md-6">Gold Plan</li>
                      <li class="col-md-6">Platinum Plan</li>
                    </ul>
                  </fieldset>
                </div>
                
                <div class="col-md-12">
                  <fieldset class="choose-payment">
                    <legend>DEPOSIT PAYMENT</legend>
                    <ul class="row list-deposit">
                      <li class="col-md-3">Paypal</li>
                      <li class="col-md-3">Paypal</li>
                      <li class="col-md-3">Paypal</li>
                      <li class="col-md-3">Paypal</li>
                    </ul>
                  </fieldset>
                </div>
                
                <div class="col-md-12">
                  <div class="row">
                    <div class="col-md-6">
                      <div>
                        <p class="amount-title">Deposit Amount (USD)</p>
                        <div class="form-group">
                          <input type="number" class="form-control" id="amount" min="1">
                          </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div>
                        <button class="btn btn-primary">Make a Deposit Now</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>            
            <div class="col-md-4">
              <div class="total-overview">Total deposit $1542,524,100</div>
              <div class="blance-review">
                <h2>BALANCE OVERVIEW</h2>
                <ul>
                  <li>PERFECTMONEY <span class="pull-right">$0.00</span></li>
                  <li>PAYEER <span class="pull-right">$0.00</span></li>
                  <li>BITCOIN <span class="pull-right">$0.00</span></li>
                  <li>PAYZA <span class="pull-right">$0.00</span></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>