<div class="topmenu">
  <nav class="navbar navbar-default">

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span><i class="icon-user"></i></span>
                  <span>Account</span></a>
                <ul class="dropdown-menu">
                      <li><a href="<?php echo $this->url('add-bank',array('controller' => 'user', 'action' => 'addbank')) ?>">Add Bank</a></li>
                      <li><a href="<?php echo $this->url('member',array('controller' => 'user', 'action' => 'member')) ?>">Member</a></li>
                      <li><a href="<?php echo $this->url('editprofile',array('controller' => 'user', 'action' => 'edit')) ?>">Edit Profile</a></li>
                      <li><a href="<?php echo $this->url('changepassword',array('controller' => 'user', 'action' => 'changepassword')) ?>">Change Password</a></li>
											<li><a href="<?php echo $this->url('logout',array('controller' => 'user', 'action' => 'logout')) ?>">Logout</a></li>
                  </ul>
              </li>
              <li>
                <a href="<?php echo $this->url('make-deposit',array('controller' => 'investment', 'action' => 'makedeposit')) ?>">
                  <span><i class="icon-total-deposit"></i></span>
                  <span>Make deposit</span>
                </a>
              </li>
              <li>
                  <a href="<?php echo $this->url('history',array('controller' => 'investment', 'action' => 'history')) ?>"> 
                    <span><i class="icon-history"></i></span>
                    <span>History</span>
                  </a>
              </li>
              <li>
                <a href="<?php echo $this->url('withdraw',array('controller' => 'investment', 'action' => 'withdraw')) ?>">
                  <span><i class="icon-total-withdraw"></i></span>
                  <span>Withdraw</span>
                </a>
              </li>
              <li>
                <a href="<?php echo $this->url('my-deposit',array('controller' => 'investment', 'action' => 'mydeposit')) ?>">
                  <span><i class="icon-last-deposit"></i></span>
                  <span>My deposit</span>
                </a>
              </li>
          </ul>
        </div>
      <!-- /.navbar-collapse -->

     <!-- /.container-fluid -->
  </nav>
</div><!--end topmenu-->