<div class="topmenu">
  <nav class="navbar navbar-default">

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span><i class="icon-user"></i></span>
                  <span>Account</span></a>
                <ul class="dropdown-menu">
                      <li><a href="#">Add Bank</a></li>
                      <li><a href="#">Member</a></li>
                      <li><a href="#">Edit Profile</a></li>
                      <li><a href="#">Change Password</a></li>
                  </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span><i class="icon-total-deposit"></i></span>
                  <span>Make deposit</span>
                </a>
              </li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
                    <span><i class="icon-history"></i></span>
                    <span>History</span>
                  </a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span><i class="icon-total-withdraw"></i></span>
                  <span>Withdraw</span>
                </a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span><i class="icon-last-deposit"></i></span>
                  <span>My deposit</span>
                </a>
              </li>
          </ul>
        </div>
      <!-- /.navbar-collapse -->

     <!-- /.container-fluid -->
  </nav>
</div><!--end topmenu-->