<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Sửa sản phẩm</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'product', 'action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'product', 'action' => 'add')) ?>" id="form-add-user" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="box">
                                        <div class="box-header"><h2>Thông tin cơ bản</h2></div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="name">Tên sản phẩm</label><span class="validation">*</span>
                                                        <input type="text" data-toggle="tooltip" value="<?php echo isset($arrayParam['post']['name'])?$arrayParam['post']['name']:'' ?>" data-placement="top" title="Nhập tên sản phẩm" class="form-control" id="name" name="name">
                                                        <p class="error"><?php echo isset($arrayParam['error']['name'])? $arrayParam['error']['name']:'' ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="slug">Slug</label><span class="validation">*</span>
                                                        <input type="text" data-toggle="tooltip" value="<?php echo isset($arrayParam['post']['slug'])?$arrayParam['post']['slug']:'' ?>" data-placement="top" title="Nhập alias cho sản phẩm" class="form-control" id="slug" name="slug">
                                                        <p class="error"><?php echo isset($arrayParam['error']['slug'])? $arrayParam['error']['slug']:'' ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                            <div class="form-group">
                                                                <label>Danh mục</label><span class="validation">*</span>
                                                                <select name="category_id" id="category_id" class="selectpicker show-tick form-control" data-live-search="true">
                                                                    <?php echo $category; ?>
                                                                </select>
                                                                <p class="error"><?php echo isset($arrayParam['error']['category_id'])? $arrayParam['error']['category_id']:'' ?></p>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                            <label>&nbsp;</label>
                                                            <div class="add-item" data-toggle="modal" data-target=".bs-category"><i class="fa fa-plus"></i></div>
                                                        </div>
                                                    </div>
                                                </div>


                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="quantity">Số lượng</label>
                                                                <input type="number" min="1" value="<?php echo isset($arrayParam['post']['quantity'])?$arrayParam['post']['quantity']:'1' ?>" class="form-control" data-toggle="tooltip" data-placement="top" title="Nhập số lượng sản phẩm" id="quantity" name="quantity">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="startday">Ngày đăng</label>
                                                                <input type="date" id="startday" value="<?php echo (isset($arrayParam['post']['startday']) && !empty($arrayParam['post']['startday']))? date('Y-m-d',$arrayParam['post']['startday']) :'' ?>"  name="startday" class="form-control" data-toggle="tooltip" data-placement="top" title="Ngày đăng">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="endday">Ngày hạ</label>
                                                                <input type="date" id="endday" value="<?php echo (isset($arrayParam['post']['endday']) && !empty($arrayParam['post']['endday']))? date('Y-m-d', $arrayParam['post']['endday']):'' ?>" class="form-control" data-toggle="tooltip" data-placement="top" title="Ngày hạ" name="endday">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                            <div class="form-group">
                                                                <label for="supplier_id">Nhà cung cấp</label><span class="validation">*</span>
                                                                <select name="supplier_id" id="supplier_id" class="selectpicker show-tick form-control" data-live-search="true">
                                                                    <option value="">-- Chọn --</option>
                                                                    <?php if($supplier): ?>
                                                                    <?php foreach ($supplier as $val): ?>
                                                                    <?php $supplierSelect = (isset($arrayParam['post']['supplier_id']) && $arrayParam['post']['supplier_id'] == $val['id'])? 'selected':'' ?>
                                                                    <option <?php echo $supplierSelect; ?> value="<?php echo $val['id']; ?>"><?php echo $val['name']; ?></option>
                                                                    <?php endforeach; ?>
                                                                    <?php endif; ?>
                                                                </select>
                                                                <p class="error"><?php echo isset($arrayParam['error']['supplier_id'])? $arrayParam['error']['supplier_id']:'' ?></p>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                            <label>&nbsp;</label>
                                                            <div class="add-item" data-toggle="modal" data-target=".bs-supplier"><i class="fa fa-plus"></i></div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                            <div class="form-group">
                                                                <label for="store_id">Chọn kho hàng</label><span class="validation">*</span>
                                                                <select name="shop_id" id="store_id" class="selectpicker show-tick form-control" data-live-search="true">
                                                                    <option value="">-- Chọn --</option>
                                                                    <?php if($shop): ?>
                                                                    <?php foreach ($shop as $val): ?>
                                                                    <?php $shopSelect = (isset($arrayParam['post']['shop_id']) && $arrayParam['post']['shop_id'] == $val['id'])? 'selected':'' ?>
                                                                    <option <?php echo $shopSelect;?> value="<?php echo $val['id']; ?>"><?php echo $val['name']; ?></option>
                                                                    <?php endforeach; ?>
                                                                    <?php endif; ?>
                                                                </select>
                                                                <p class="error"><?php echo isset($arrayParam['error']['shop_id'])? $arrayParam['error']['shop_id']:'' ?></p>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                            <label>&nbsp;</label>
                                                            <div class="add-item" data-toggle="modal" data-target=".bs-store"><i class="fa fa-plus"></i></div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6 col-md-8 col-sm-6 col-xs-6">
                                                            <div class="form-group">
                                                                <label for="trademark_id">Thương hiệu</label><span class="validation">*</span>
                                                                <select name="trademark_id" id="trademark_id" class="selectpicker show-tick form-control" data-live-search="true">
                                                                    <option value="">-- Chọn --</option>
                                                                    <?php if($trademark): ?>
                                                                    <?php foreach ($trademark as $val): ?>
                                                                    <?php $trademarkSelect = (isset($arrayParam['post']['trademark_id']) && $arrayParam['post']['trademark_id'] == $val['id'])? 'selected':'' ?>
                                                                    <option <?php echo $trademarkSelect; ?> value="<?php echo $val['id']; ?>"><?php echo $val['name']; ?></option>
                                                                    <?php endforeach; ?>
                                                                    <?php endif; ?>
                                                                </select>
                                                                <p class="error"><?php echo isset($arrayParam['error']['trademark_id'])? $arrayParam['error']['trademark_id']:'' ?></p>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6 col-md-4 col-sm-6 col-xs-6">
                                                            <label>&nbsp;</label>
                                                            <div class="add-item" data-toggle="modal" data-target=".bs-trademark"><i class="fa fa-plus"></i></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="box">
                                        <div class="box-header"><h2>Thư viện ảnh</h2></div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="image">Ảnh đại điện</label><span class="validation">*</span>
                                                        <input type="file" name="image" class="form-control" id="image">
                                                        <p class="error"><?php echo isset($arrayParam['error']['image'])? $arrayParam['error']['image']:'' ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="image_gallery">Ảnh gallery</label>
                                                        <input name="gallery[]" multiple type="file" class="form-control" id="image_gallery">
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                    </div>

                                    <div class="box">
                                        <div class="box-header"><h2><i class="fa fa-plus"></i> Thông tin website</h2></div>
                                        <div class="box-body box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="status" value="0">
                                                                        <input type="checkbox" name="status" id="promote" value="1" <?php echo (!isset($arrayParam['post']['status']))?'checked':((isset($arrayParam['post']['status'])) && $arrayParam['post']['status'] == 1)?'checked':'' ?>>
                                                                        Đăng
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="heighlight" value="0">
                                                                        <input type="checkbox" name="heighlight" id="heighlight" value="1" <?php echo ((isset($arrayParam['post']['heighlight'])) && $arrayParam['post']['heighlight'] == 1)?'checked':'' ?>>
                                                                        Hiện ở trang chủ
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="new" value="0">
                                                                        <input type="checkbox" name="new" id="promote" value="1" <?php echo ((isset($arrayParam['post']['new'])) && $arrayParam['post']['new'] == 1)?'checked':'' ?>>
                                                                        Sản phẩm mới
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="hot" value="0">
                                                                        <input type="checkbox" name="hot" id="promote" value="1" <?php echo ((isset($arrayParam['post']['hot'])) && $arrayParam['post']['hot'] == 1)?'checked':'' ?>>
                                                                        Sản phẩm hot
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="sticky" value="0">
                                                                        <input type="checkbox" name="sticky" id="promote" value="1" <?php echo ((isset($arrayParam['post']['sticky'])) && $arrayParam['post']['sticky'] == 1)?'checked':'' ?>>
                                                                        Sản phẩm bán chạy
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <input type="hidden" name="promote" value="0">
                                                                        <input type="checkbox" name="promote" id="promote" value="1" <?php echo ((isset($arrayParam['post']['promote'])) && $arrayParam['post']['promote'] == 1)?'checked':'' ?>>
                                                                        Sản phẩm quảng cáo
                                                                    </label>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="box">
                                        <div class="box-header"><h2>Thông tin về giá</h2></div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="cost">Giá nhập</label><span class="validation">*</span>
                                                        <input type="number" min="0" class="form-control" value="<?php echo isset($arrayParam['post']['cost'])?$arrayParam['post']['cost']:'' ?>" name="cost" data-toggle="tooltip" data-placement="top" title="Giá nhập hàng (giá gốc)" id="cost">
                                                        <p class="error"><?php echo isset($arrayParam['error']['cost'])? $arrayParam['error']['price']:'' ?></p>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="price">Giá bán</label><span class="validation">*</span>
                                                        <input type="number" min="0" class="form-control" value="<?php echo isset($arrayParam['post']['price'])?$arrayParam['post']['price']:'' ?>" name="price" id="price" data-toggle="tooltip" data-placement="top" title="Nhập giá bán">
                                                        <p class="error"><?php echo isset($arrayParam['error']['price'])? $arrayParam['error']['price']:'' ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="weight">Giảm giá (%)</label>
                                                                <input type="number" name="sale" min="0" max="100" value="<?php echo isset($arrayParam['post']['sale'])?$arrayParam['post']['sale']:'' ?>" class="form-control" id="sale" data-toggle="tooltip" data-placement="top" title="Giảm giá ( min: 0 - max: 100 )">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="tax">Thuế</label>
                                                        <input type="number" min="0" max="30" value="<?php echo isset($arrayParam['post']['tax'])?$arrayParam['post']['tax']:'0' ?>" name="tax" class="form-control" data-toggle="tooltip" data-placement="top" title="Thuế (VAT)" id="tax">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="box">
                                        <div class="box-header"><h2>Thông tin về màu sắc & kích thước</h2></div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="color">Màu sắc</label>
                                                        <input type="text" class="form-control" value="<?php echo isset($arrayParam['post']['color'])?$arrayParam['post']['color']:'' ?>" data-toggle="tooltip" data-placement="top" title='Nhập màu sắc cho sản phẩm ( cách nhau bởi dấu "," )' name="color">
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="size">Size</label>
                                                        <input type="text" class="form-control" value="<?php echo isset($arrayParam['post']['size'])?$arrayParam['post']['size']:'' ?>" id="size" data-toggle="tooltip" data-placement="top" title='Nhập Size cho sản phẩm ( cách nhau bởi dấu "," )' name="size">
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="sort">Sắp xếp</label>
                                                                <input type="number" min="0" value="<?php echo isset($arrayParam['post']['sort'])?$arrayParam['post']['sort']:'' ?>" class="form-control" id="sort" name="sort" placeholder="0" data-toggle="tooltip" data-placement="top" title='Nhập thử tự hiển thị'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <label for="weight">Khối lượng</label>
                                                                <input type="number" min="0" value="<?php echo isset($arrayParam['post']['gram'])?$arrayParam['post']['gram']:'' ?>" class="form-control" name="weight" id="weight" data-toggle="tooltip" data-placement="top" title="Nhập khối lượng sản phẩm (không bắt buộc)">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>


                                            </div>
                                        </div>
                                    </div>


                                    <div class="box">
                                        <div class="box-header"><h2><i class="fa fa-plus"></i> Thông tin SEO</h2></div>
                                        <div class="box-body box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="title">Meta title</label>
                                                        <input type="text" class="form-control" name="title" value="<?php echo isset($arrayParam['post']['title'])?$arrayParam['post']['title']:'' ?>" id="title" data-toggle="tooltip" data-placement="top" title="Nhập tiêu đề SEO">
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="keyword">Meta keyword</label>
                                                        <input type="text" name="keyword" value="<?php echo isset($arrayParam['post']['keyword'])?$arrayParam['post']['keyword']:'' ?>" class="form-control" id="keyword" data-toggle="tooltip" data-placement="top" title="Nhập từ khóa SEO">
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="description">Meta description</label>
                                                        <textarea class="form-control" rows="3" name="description" data-toggle="tooltip" data-placement="top" title="Nhập mô tả SEO"><?php echo isset($arrayParam['post']['description'])?$arrayParam['post']['description']:'' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="box">
                                        <div class="box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="except">Mô tả ngắn</label>
                                                        <textarea class="form-control" id="" rows="3" name="excerpt" data-toggle="tooltip" data-placement="top" title="Mô tả ngắn"><?php echo isset($arrayParam['post']['except'])?$arrayParam['post']['except']:'' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <div class="box">
                                        <div class="box-bs">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <label for="content">Nội dung</label>
                                                        <textarea class="form-control" id="" rows="3" name="content" data-toggle="tooltip" data-placement="top" title="Nội dung"><?php echo isset($arrayParam['post']['content'])?$arrayParam['post']['content']:'' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                    <button type="submit" name="save" value="save" class="btn btn-default btn-custom add">Lưu</button>
                                    <button type="submit" name="save-news" value="save-news" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="modal fade bs-category modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm nhóm hàng</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="category_ajax">Tên nhóm</label>
                        <input type="text" class="form-control" id="category_name" placeholder="Tên nhóm">
                        <p class="error" id="category_name_error"></p>
                    </div>
                    <div class="form-group">
                        <label for="category_slug">Slug</label>
                        <input type="text" class="form-control" id="category_slug" placeholder="Slug">
                        <p class="error" id="category_slug_error"></p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="form-group">
                            <label>Nhóm cha</label>
                            <div class="form-control-category">
                                <select name="parent" id="add-category" class="selectpicker show-tick form-control" data-live-search="true">
                                </select>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" id="btn-category-add" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>

<div class="modal fade bs-store modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm kho hàng</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="store_name">Tên kho</label>
                        <input type="text" name="store" class="form-control" id="store_name" placeholder="Tên kho hàng">
                        <p class="error" id="store_name_error"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" id="btn-store-add" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>

<div class="modal fade bs-supplier modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm nhà cung cấp</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="supplier">Tên nhà cung cấp</label>
                        <input type="text" name="supplier" class="form-control" id="supplier_name">
                        <p class="error" id="supplier_name_error"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" id="btn-supplier-add" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>


<div class="modal fade bs-trademark modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm thương hiệu</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="trademark_name">Tên thương hiệu</label>
                        <input type="text" name="trademark" value="" class="form-control" id="trademark_name">
                        <p class="error" id="trademark_name_error"></p>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <label for="trademark_slug">Slug</label>
                        <input type="text" name="trademark_slug" value="" class="form-control" id="trademark_slug">
                        <p class="error" id="trademark_slug_error"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" id="btn-trademark-add" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.bs-category').on('shown.bs.modal', function () {
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'ajaxloadcategory')) ?>",
                data: {},
                dataType: 'JSON',
                beforeSend: function( xhr ) {
                     $(".form-control-category").addClass('on');
                },
                success: function(data){
                    $("#add-category").empty().append(data.data);
                    $('#add-category').selectpicker('refresh');
                    $(".form-control-category").removeClass('on');
                }    
           });
        });
        $("#btn-category-add").on('click', function(){
            var name = $("#category_name").val();
            var slug = $('#category_slug').val();
            var category = $("#add-category").val();
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'ajaxaddcategory')) ?>",
                data: {'name': name, 'slug': slug , 'parent': category},
                dataType: 'JSON',
                success: function(data){
                    if(data.error){
                        $("#category_name_error").empty().append(data.error.name);
                        $("#category_slug_error").empty().append(data.error.slug);
                    }else{
                        $('.bs-category').modal('hide');
                        $("#category_name").val('');
                        $('#category_slug').val('');
                        $("#category_id").empty().append(data.reloadCategory);
                        $('#category_id').selectpicker('refresh');
                    }
                }    
           });
        });
    });
    
    // supplider
    $("#btn-supplier-add").on('click', function(){
        var name = $("#supplier_name").val();
        $.ajax({
            type:"POST",
            url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'ajaxaddsupplier')) ?>",
            data: {'name': name},
            dataType: 'JSON',
            success: function(data){
                if(data.error){
                    $("#supplier_name_error").empty().append(data.error.name);
                }else{
                    $('.bs-supplier').modal('hide');
                    $("#supplier_name").val('');
                    $("#supplier_name_error").empty();
                    $("#supplier_id").empty().append(data.reloadSupplier);
                    $('#supplier_id').selectpicker('refresh');
                }
            }    
       });
    });
    
    // store
    $("#btn-store-add").on('click', function(){
        var name = $("#store_name").val();
        $.ajax({
            type:"POST",
            url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'ajaxaddstore')) ?>",
            data: {'name': name},
            dataType: 'JSON',
            success: function(data){
                if(data.error){
                    $("#store_name_error").empty().append(data.error.name);
                }else{
                    $('.bs-store').modal('hide');
                    $("#store_name").val('');
                    $("#store_name_error").empty();
                    $("#store_id").empty().append(data.reloadShop);
                    $('#store_id').selectpicker('refresh');
                }
            }    
       });
    });
    // trademark
    $("#btn-trademark-add").on('click', function(){
        var name = $("#trademark_name").val();
        var slug = $("#trademark_slug").val();
        $.ajax({
            type:"POST",
            url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'ajaxaddtrademark')) ?>",
            data: {'name': name, 'slug': slug},
            dataType: 'JSON',
            success: function(data){
                if(data.error){
                    $("#trademark_name_error").empty().append(data.error.name);
                    $("#trademark_slug_error").empty().append(data.error.slug);
                }else{
                    $('.bs-trademark').modal('hide');
                    $("#trademark_name").val('');
                    $("#trademark_slug").val('');
                    $("#trademark_name_error").empty();
                    $("#trademark_slug_error").empty();
                    $("#trademark_id").empty().append(data.reloadTrademark);
                    $('#trademark_id').selectpicker('refresh');
                }
            }    
       });
    });


</script>