<form action="<?php echo $current_link; ?>" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row function-title">
            <div class="col-lg-12">
                <h1>Sản phẩm</h1>
            </div>
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        <select name="function" class="form-control selected-custom">
                            <option>--Chức năng--</option>
                            <option value="delete">Xóa</option>
                            <option value="published">Đăng</option>
                            <option value="unpublished">Ẩn</option>
                            <option value="sort">Sắp xếp</option>
                        </select>
                        <button type="submit" name="apply" class="btn btn-default btn-custom apply">Thực hiện</button>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><a href="<?php echo $this->url('backend', array('controller' => 'product', 'action' => 'add')); ?>" class="btn btn-default btn-custom pull-right">Thêm mới</a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="filter"> 
                                <fieldset>
                                    <legend>Tìm kiếm</legend>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="row form-horizontal">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="keyword" class="col-lg-3 col-md-4 control-label">Từ khóa</label>
                                                    <div class="col-lg-9 col-md-8 col-sm-12">
                                                        <input type="text" value=""  name="textSearch" class="form-control" id="keyword">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="keyword" class="col-lg-3 col-md-4 control-label">Tìm theo</label>
                                                    <div class="col-lg-9 col-md-8 col-sm-12">
                                                        <label for="search-name" class="radio-inline">
                                                            <input type="radio" checked="" id="search-name" name="group-search" value="name"> Tên sản phẩm
                                                        </label>
                                                        <label for="search-id" class="radio-inline">
                                                            <input type="radio" id="search-id" name="group-search" value="id"> Mã sản phẩm
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Danh mục</label>
                                            <div class="col-lg-9 col-md-8">
                                                <select id="type" name="type" class="selectpicker show-tick form-control" data-live-search="true">
                                                        <option value="">-- Chọn --</option>
                                                        <?php foreach ($type as $value): ?>
                                                        <option value="<?php echo $value['id']; ?>"><?php echo $value['name']; ?></option>
                                                        <?php endforeach; ?>
                                                      </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button type="button" id="btn-search" class="btn btn-default btn-custom">Tìm</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div> <!-- end search -->

                        <div class="col-lg-12">
                            <div class="form-table">
                                <?php if($list): ?>
                                <table id="table-data" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                            <th id="key" class="name column_name no-sort">
                                                    <?php
                                                        if(isset($arrayParam['sort']) && $arrayParam['sort'] == 'id' && isset($arrayParam['order']) && !empty($arrayParam['order'])):
                                                            $class = $arrayParam['order'];
                                                            $link = $this->url($this->route, array('controller' => 'product', 'action' => 'index')). implode('', $paramSort);
                                                            $icon = 'fa-sort-'.$arrayParam['order'];
                                                        else:
                                                            $arrIdSort = $paramSort;
                                                            if(!isset($arrIdSort['sort']) || $arrIdSort['sort'] != 'id'){
                                                                if(isset($arrIdSort['sort']) && $arrIdSort['sort'] != 'id'){
                                                                    unset($arrIdSort['sort']);
                                                                }
                                                                $arrId = array();
                                                                if(isset($arrIdSort['page'])){
                                                                    $arrId['page'] = $paramSort['page'];
                                                                }
                                                                if(isset($arrIdSort['type'])){
                                                                    $arrId['type'] = $paramSort['type'];
                                                                }
                                                                $arrId['sort'] = '/sort/id';
                                                                $arrIdSort = array_merge($arrId, $arrIdSort);
                                                            }
                                                            $arrIdSort['order'] = '/order/asc';
                                                            $class = '';
                                                            $link = $this->url($this->route, array('controller' => 'product', 'action' => 'index')). implode('', $arrIdSort);
                                                            $icon = 'fa-sort-desc';
                                                        endif;
                                                    ?>
                                                    <a class="<?php echo $class ?>" href="<?php echo $link; ?>">Mã <i class="fa <?php echo $icon; ?>"></i></a>
                                                </th>
                                                <th>
                                                    <?php
                                                        if(isset($arrayParam['sort']) && $arrayParam['sort'] == 'name' && isset($arrayParam['order']) && !empty($arrayParam['order'])):
                                                            $class = $arrayParam['order'];
                                                            $link = $this->url($this->route, array('controller' => 'product', 'action' => 'index')). implode('', $paramSort);
                                                            $icon = 'fa-sort-'.$arrayParam['order'];
                                                        else:
                                                            $paramFullnameSort = $paramSort;

                                                            if(!isset($paramFullnameSort['sort']) || $paramFullnameSort['sort'] != 'name'){
                                                                if(isset($paramFullnameSort['sort']) && $paramFullnameSort['sort'] != 'name'){
                                                                    unset($paramFullnameSort['sort']);
                                                                }
                                                                $arrName = array();
                                                                if(isset($paramFullnameSort['page'])){
                                                                    $arrName['page'] = $paramFullnameSort['page'];
                                                                }
                                                                if(isset($paramFullnameSort['type'])){
                                                                    $arrName['type'] = $paramFullnameSort['type'];
                                                                }
                                                                $arrName['sort'] = '/sort/name';
                                                                $paramFullnameSort = array_merge($arrName, $paramFullnameSort);
                                                            }

                                                            $paramFullnameSort['order'] = '/order/asc';
                                                            $class = '';
                                                            $link = $this->url($this->route, array('controller' => 'product', 'action' => 'index')). implode('', $paramFullnameSort);
                                                            $icon = 'fa-sort-desc';
                                                        endif;
                                                    ?>
                                                    <a class="<?php echo $class; ?>" href="<?php echo $link; ?>">Tên sản phẩm <i class="fa <?php echo $icon; ?>"></i></a>
                                                </th>
                                                <th>
                                                    <?php
                                                        if(isset($arrayParam['sort']) && $arrayParam['sort'] == 'category_id' && isset($arrayParam['order']) && !empty($arrayParam['order'])):
                                                            $class = $arrayParam['order'];
                                                            $link = $this->url($this->route, array('controller' => 'product', 'action' => 'index')). implode('', $paramSort);
                                                            $icon = 'fa-sort-'.$arrayParam['order'];
                                                        else:
                                                            $paramEmailSort = $paramSort;
                                                            if(!isset($paramEmailSort['category_id']) || $paramEmailSort['sort'] != 'category_id'){
                                                                if(isset($paramEmailSort['sort']) && $paramEmailSort['sort'] != 'category_id'){
                                                                    unset($paramEmailSort['sort']);
                                                                }
                                                                $arrEmail = array();
                                                                if(isset($paramEmailSort['page'])){
                                                                    $arrEmail['page'] = $paramEmailSort['page'];
                                                                }
                                                                if(isset($paramEmailSort['type'])){
                                                                    $arrEmail['type'] = $paramEmailSort['type'];
                                                                }
                                                                $arrEmail['sort'] = '/sort/category_id';
                                                                $paramEmailSort = array_merge($arrEmail, $paramEmailSort);
                                                            }
                                                            $paramEmailSort['order'] = '/order/asc';
                                                            $class = '';
                                                            $link = $this->url($this->route, array('controller' => 'product', 'action' => 'index')). implode('', $paramEmailSort);
                                                            $icon = 'fa-sort-desc';
                                                        endif;
                                                    ?>
                                                    <a class="<?php echo $class; ?>" href="<?php echo $link; ?>">Danh mục <i class="fa <?php echo $icon; ?>"></i></a>
                                                </th>
                                            <th class="price column_price">Giá nhập</th>
                                            <th class="price column_price">Giá bán</th>
                                            <th class="weight column_weight">Vị trí</th>
                                            <th class="quantity column_quantity">Số lượng</th>
                                            <th class="status column_status">Trang thái</th>
                                        </tr>
                                    </thead>
                                    <tbody>






                                        <?php foreach ($list as $value): ?>
                                        <tr id="product-<?php echo $value['id']; ?>">
                                            <td><input type="checkbox" value="<?php echo $value['id']; ?>" name="check-all[]" class="form-checkbox check-all"></td>
                                            <td><?php echo $value['id']; ?></td>
                                            <td class="column-title column_name">
                                                <strong class="key-title"><?php echo $value['name']; ?></strong>
                                                <div class="row-action">
                                                    <span class="edit">
                                                        <a class="icon-edit" href="<?php echo $this->url('backend', array('controller' => 'product', 'action' => 'edit', 'id' => $value['id'])); ?>" title="Sửa"><i class="fa fa-pencil-square-o"></i></a>
                                                    </span>
                                                    <span class="quick-edit">
                                                        <a data-id="<?php echo $value['id']; ?>"  title="Sửa nhanh" href="javascript:void(0)">Sửa nhanh</a> | 
                                                    </span>
                                                    <span class="delete">
                                                        <a class="icon-delete" data-id="<?php echo $value['id']; ?>" data-toggle="modal" data-target=".modal-delete-taxonomy" title="Delete"><i class="fa fa-times"></i></a> 
                                                    </span>
                                                    <span class="view">
                                                        <a href="#"><i class="fa fa-refresh"></i></a>
                                                    </span>
                                                </div>
                                            </td>
                                            <td class="column_category"><?php echo $value['category-name']; ?></td>
                                            <td class="column_price"><?php echo number_format(round($value['price'], -3),0,'.','.'); ?></td>
                                            <td class="column_price"><?php echo number_format(round($value['price'], -3),0,'.','.'); ?></td>
                                            <td class="column_weight"><input type="number" min="0" value="<?php echo $value['sort']; ?>" name="sort[<?php echo $value['id'] ?>]" class="form-control update_weight"></td>
                                            <td class="column_quantity"><?php echo $value['quantity']; ?></td>
                                            <td class="column_status status">
                                                <?php echo ($value['status'] == 1)? '<a data-status='.json_encode(array('id' => $value['id'], 'status' => 1)).' href="javascript:void(0)" title="Hiển thị" class="active fa fa-check-circle"></a>': '<a data-status='.json_encode(array('id' => $value['id'], 'status' => 0)).' title="Không hiển thị" class="unactive fa fa-minus-circle"></a>'; ?>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>

                                    </tbody>
                                </table>
                                <?php else: ?>
                                <div class="alert alert-info" role="alert">Không có sản phẩm nào. </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
			<?php
				echo $this->paginationControl($paginator, 'Elastic', 'partial/pagination.phtml',array('name' => 'backend','controller' => 'product','action' => 'index', 'routeParam' => $routeParam));
			?>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.form-table .table>tbody>tr>td span.quick-edit a').on('click', function(){
            $(".form-table .table>tbody>tr").removeAttr('style');
            $(this).closest('tr').css('display', 'none');
            $('.edit-row').remove();
            var id = $(this).attr('data-id');
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'quickedit')) ?>",
                data: {'id': id},
                dataType: 'JSON',
                beforeSend: function(){
                },
                success: function(data){
                     $("#product-"+id).addClass('tr-quick-edit').after(data.html);
                }    
            });
//             $('.selectpicker').selectpicker('refresh');
//             $('.selectpicker').selectpicker('render');
//             $('.selectpicker').selectpicker('show');
        });
        // quick edit
        $('.form-table').on('click', '.table>tbody>tr>td #quick-edit', function(){
            var id = $("#id").val();
            var name = $("#name").val();
            var slug = $("#slug").val();
            var color = $("#color").val();
            var size = $("#size").val();
            var cost = $("#cost").val();
            var price = $("#price").val();
            var sale = $("#sale").val();
            var tax = $("#tax").val();
            var sort = $("#sort").val();
            var highlight = $("input[name=highlight]").is(':checked')? 1 : 0;
            var hot = $("input[name=hot]").is(':checked')? 1 : 0;
            var sticky = $("input[name=sticky]").is(':checked')? 1 : 0;
            var promote = $("input[name=promote]").is(':checked')? 1 : 0;
            var category_id = $("#basic-quick-edit").val();
            
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'quickupdate')) ?>",
                data: {'id': id, 'name': name, 'slug': slug, 'color': color, 
                       'size': size, 'cost': cost, 'price': price, 'sale': sale, 
                       'sort': sort, 'highlight': highlight, 'hot': hot, 'sticky': sticky, 
                       'promote': promote, 'category_id' : category_id},
                dataType: 'JSON',
                beforeSend: function(){
                },
                success: function(data){
                    if(data.error){
                        console.log((data.error).length);
                        $("#error_name").empty().append(data.error.name);
                        $("#error_slug").empty().append(data.error.slug);
                        $("#error_cost").empty().append(data.error.cost);
                        $("#error_price").empty().append(data.error.price);
                    }
                    console.log(data);
                     //$("#product-"+id).addClass('tr-quick-edit').after(data.html);
                }    
            });
        });

        $('.form-table').on('click', '.table>tbody>tr .btn-back', function(){
             $(".form-table .table>tbody>tr").removeAttr('style');
             $('.edit-row').remove();
        });
        // search
        var param = '<?php echo json_encode($paramSort); ?>';
        $("#btn-search").on('click', function(){
            var textSearch = $("#keyword").val();
            var type = $("#type").val();
            var sort = $("[name=group-search]:checked").val();
            if(textSearch.length === 0){
                alert('Bạn chưa nhập từ khóa cần tìm.');
                return false;
            }
            var data = jQuery.parseJSON(param);
            var uri = '';
            uri += '<?php echo $this->url('backend', array('controller' => 'product', 'action' => 'index')); ?>';
            uri += data.page ? data.page: '';
            uri += (type.length !== 0 && $.isNumeric(type))?'/type/'+ type :'';
            //uri += data.sort ? data.sort: '';
            uri += (sort.length !== 0)?'/sort/'+ sort :'';
            uri += data.order ? data.order: '';
            uri += (textSearch.length !== 0 )?'/textSearch/'+ textSearch :'';
            window.location.href = uri;
        });
        // change status
        $(".form-table .table>tbody>tr>td.column_status a").on('click', function(){
            var data = $(this).attr('data-status');
            var loadData = jQuery.parseJSON(data);
            var obj = { 'id' : loadData.id, 'status': loadData.status };
            if (confirm('Bạn có muốn thay đổi trạng thái không?')) {
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'changestatus')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(data){
                        location.reload();
                    }    
               });
            }   
        });
        
        // delete product 
        $(".form-table .table>tbody>tr>td .row-action a.icon-delete").on('click', function(){
            var id = $(this).attr('data-id');
            var obj = { 'id' : id};
            if (confirm('Bạn có muốn xóa không?')) {
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'product', 'action' => 'deleteproduct')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(data){
                        if(data.message.length > 0){
                            alert(data.message);
                        }else{
                            location.reload();
                        }   
                    }    
               });
            }   
        });
   
  
});
</script>