<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm danh mục</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'category','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin chung</h2></div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="name">Tên <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Tên danh mục ( Đây là trường bắt buộc nhập ).">?</span></label>
                                                    <input type="text" class="form-control" id="name" placeholder="Tên">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="slug">Slug <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Alias ( Đây là trường bắt buộc nhập - viết liền không dấu - cách nhau bởi đấu '-'. VD: product-name ).">?</span></label>
                                                    <input type="text" class="form-control" id="slug" placeholder="Slug">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="category">Danh mục cha <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Chọn danh mục cha ( Đây là trường bắt buộc chọn ).">?</span></label>
                                                            <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                                <option>cow</option>
                                                                <option>bull</option>
                                                                <option class="get-class" disabled>ox</option>
                                                                <optgroup label="test" data-subtext="another test">
                                                                    <option>ASD</option>
                                                                    <option selected>Bla</option>
                                                                    <option>Ble</option>
                                                                </optgroup>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="description">Mô tả <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <textarea class="form-control" rows="3" name="description"></textarea>
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="weight">Vị trí <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                            <input type="number" value="0" class="form-control" id="weight" placeholder="Vị trí">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input checked type="checkbox" name="status"> Trạng thái
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Cài đặt SEO</h2></div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="title">Tiêu đề SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <input type="text" class="form-control" id="title" placeholder="Tiêu đề">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="keyword">Từ khóa SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <input type="text" class="form-control" id="keyword" placeholder="keyword">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="description">Mô tả SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <textarea class="form-control" rows="3" name="seodescription"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="box-footer">
                                        <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
