<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm danh mục</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'category','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
						<div class="row">
							<div class="col-lg-12 language">
								<ul class="nav nav-tabs" role="tablist">
									<li role="presentation" class="active"><a href="#vi" data-lang="vi" aria-controls="vi" role="tab" data-toggle="tab">Tiếng Việt</a></li>
									<li role="presentation"><a href="#en" data-lang="en" aria-controls="en" role="tab" data-toggle="tab">English</a></li>
								</ul>
							</div>
						</div>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin chung</h2></div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
														<label for="name">Tên <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Tên danh mục ( Đây là trường bắt buộc nhập ).">?</span></label>
														<input type="text" class="form-control" value="" name="name[vi]" placeholder="Tên" data-name ="Tên">
													</div>
													<div class="box-language lang-en hidden">
														<label for="name">Name <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Category Name.">?</span></label>
														<input type="text" class="form-control" value="" name="name[en]" placeholder="name">
													</div>
													
                                                    
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
														<label for="slug">Slug <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Alias ( Đây là trường bắt buộc nhập - viết liền không dấu - cách nhau bởi đấu '-'. VD: product-name ).">?</span></label>
														<input type="text" class="form-control" placeholder="Slug" name="slug[vi]">
													</div>
													<div class="box-language lang-vi">
														<label for="slug">Slug <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Alias">?</span></label>
														<input type="text" class="form-control hidden" name="slug[en]" placeholder="Slug">
													</div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="category">Danh mục cha <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Chọn danh mục cha ( Đây là trường bắt buộc chọn ).">?</span></label>
                                                            <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                                <option selected>-- Choose --</option>
                                                                <option>Category</option>
                                                                <option> &nbsp; &nbsp;Parent 1</option>
                                                                <option> &nbsp; &nbsp; &nbsp; &nbsp;Child 1</option>
                                                                <option> &nbsp; &nbsp; &nbsp; &nbsp;Child 2</option>
                                                                <option> &nbsp; &nbsp; &nbsp; &nbsp;Child 3</option>
                                                                <option> &nbsp; &nbsp;Parent 2</option>
                                                                <option> &nbsp; &nbsp;Parent 3</option>
                                                                <option> &nbsp; &nbsp;Parent 4</option>
                                                                <option> Category 1</option>
                                                                <option> Category 2</option>
                                                                <option> Category 3</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="description">Mô tả <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <textarea class="form-control" rows="3" name="description[vi]"></textarea>
													<textarea class="form-control hidden" rows="3" name="description[en]"></textarea>
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <label for="weight">Vị trí <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                            <input type="number" value="0" class="form-control" id="weight" name="weigh[vi]" placeholder="Vị trí">
															<input type="number" value="0" class="form-control hidden" id="weight" name="weigh[en]" placeholder="Weight">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <span><input checked type="checkbox" name="status[vi]"> Trạng thái</span>
																	<span class="hidden"><input checked type="checkbox" name="status[en]"> Published</span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Cài đặt SEO</h2></div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="title">Tiêu đề SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <input type="text" class="form-control" name="metatitle[vi]" placeholder="Tiêu đề">
													<input type="text" class="form-control hidden" name="metatitle[en]" placeholder="Meta title">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="keyword">Từ khóa SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <input type="text" class="form-control" name="metakeyword[vi]" placeholder="Từ khóa seo">
													<input type="text" class="form-control hidden" name="metakeyword[en]" placeholder="Meta keyword">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="description">Mô tả SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                    <textarea class="form-control" rows="3" name="metadescriptionp[vi]"></textarea>
													<textarea class="form-control hidden" rows="3" name="metadescriptionp[en]"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="box-footer">
                                        <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>