<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm danh mục</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'category','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'category', 'action' => 'add')) ?>" id="form-add-category" method="post" enctype="multipart/form-data">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="box">
                                        <div class="box-language lang-vi">
                                            <div class="box-header"><h2>Thông tin chung</h2></div>
                                        </div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="box-language lang-vi">
                                                                    <label for="taxonomy">Nhóm<span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc.">?</span></label>
                                                                    <select id="taxonomy" name="taxonomy_id" class="selectpicker show-tick form-control" data-live-search="true">
                                                                        <option value="">-- Chọn --</option>
                                                                        <?php if($taxonomyList): ?>
                                                                        <?php foreach ($taxonomyList as $value): ?>
                                                                        <option <?php echo ((isset($arrayParam['post']['taxonomy_id'])) && ($value['id'] == $arrayParam['post']['taxonomy_id']))?'selected': '' ?> value="<?php echo $value['id']; ?>"><?php echo $value['name']; ?></option>
                                                                        <?php endforeach; ?>
                                                                        <?php endif; ?>
                                                                    </select>
                                                                    <p class="error"><?php echo isset($arrayParam['error']['taxonomy_id'])? $arrayParam['error']['taxonomy_id']:'' ?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <div class="box-language lang-vi">
                                                            <label for="name">Tên danh mục <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc.">?</span></label>
                                                            <input type="text" id="post-name" class="form-control" value="<?php echo isset($arrayParam['post']['name'])?$arrayParam['post']['name']:'' ?>" name="name" placeholder="Tên">
                                                            <p class="error"><?php echo isset($arrayParam['error']['name'])? $arrayParam['error']['name']:'' ?></p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <div class="box-language lang-vi">
                                                            <label for="slug">Slug <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc.">?</span></label>
                                                            <input type="text" id="post-alias" class="form-control" placeholder="Slug" value="<?php echo isset($arrayParam['post']['slug'])?$arrayParam['post']['slug']:'' ?>" name="slug">
                                                            <p class="error"><?php echo isset($arrayParam['error']['slug'])? $arrayParam['error']['slug']:'' ?></p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="box-language lang-vi">
                                                                    <label for="category">Chọn danh mục cha <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                                    <div class="form-control-category">
                                                                        <select id="category" name="parent" class="selectpicker show-tick form-control" data-live-search="true">
                                                                            <option value="0">-- Chọn --</option>
                                                                        </select>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <div class="box-language lang-vi">
                                                            <label for="excerpt">Mô tả <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                            <textarea class="form-control" rows="3" name="excerpt"></textarea>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="box-language lang-vi">
                                                                    <label for="weight">Vị trí <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                                    <input type="number" value="0" min="0" class="form-control" id="weight" name="sort" placeholder="Vị trí">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <div class="form-group">
                                                                <div class="box-language lang-vi">
                                                                    <div class="checkbox">
                                                                        <label>
                                                                            <span>
                                                                            <input type="hidden" name="status" value="0">
                                                                            <input type="checkbox" name="status" id="status" value="1" <?php echo (!isset($arrayParam['post']['status']))?'checked':((isset($arrayParam['post']['status'])) && $arrayParam['post']['status'] == 1)?'checked':'' ?>>
                                                                            
                                                                            Trạng thái</span>
                                                                        </label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="box">
                                        <div class="box-language lang-vi">
                                            <div class="box-header"><h2>Cài đặt SEO</h2></div>
                                        </div>
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <div class="box-language lang-vi">
                                                            <label for="title">Tiêu đề SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                            <input type="text" class="form-control" name="title" placeholder="Tiêu đề">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <div class="box-language lang-vi">
                                                            <label for="keyword">Từ khóa SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                            <input type="text" class="form-control" name="keyword" placeholder="Từ khóa seo">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="form-group">
                                                        <div class="box-language lang-vi">
                                                            <label for="description">Mô tả SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                            <textarea class="form-control" rows="3" name="description"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="box-footer">
                                                <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                                <button type="submit" name="save" value="save" class="btn btn-default btn-custom add">Lưu</button>
                                                <button type="submit" name="save-news" value="save-news" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>                                       
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    jQuery(document).ready(function($){
        var id = $("#taxonomy").val();
        if(id){
            var category = <?php echo isset($arrayParam['post']['parent'])? $arrayParam['post']['parent']: '0'; ?>;
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'category', 'action' => 'loadcategory')) ?>",
                data: { 'id' : id, 'category_id':category, 'action': 'add'},
                dataType: 'JSON',
                beforeSend: function( xhr ) {
                     $(".form-control-category").addClass('on');
                },
                success: function(data){
                    $("#category").empty().append(data.data);
                    $('#category').selectpicker('refresh');
                    $(".form-control-category").removeClass('on');
                }    
           });
        }
        
        $("#taxonomy").on('change', function(){
            var taxonomyId = this.value;
            $.ajax({
                type:"POST",
                url: "<?php echo $this->url($this->route, array('controller' => 'category', 'action' => 'loadcategory')) ?>",
                data: { 'id' : taxonomyId},
                dataType: 'JSON',
                beforeSend: function( xhr ) {
                     $(".form-control-category").addClass('on');
                },
                success: function(data){
                    $("#category").empty().append(data.data);
                    $('#category').selectpicker('refresh');
                    $(".form-control-category").removeClass('on');
                }    
           });
        });
    });
</script>