<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Danh mục</h1>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <select class="form-control selected-custom">
                        <option value="">----</option>
                        <option value="delete">Xóa vĩnh viễn</option>
                        <option value="delete_flag">Xóa tạm thời</option>
                        <option value="published">Đăng</option>
                        <option value="unpublished">Tạm dừng</option>
                        <option value="update_weight">Cập nhật vị trí</option>
                    </select>
                    <button type="button" class="btn btn-default btn-custom apply">Thực hiện</button>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><a href="<?php echo $this->url('backend', array('controller' => 'category', 'action' => 'add')) ?>" class="btn btn-default btn-custom pull-right">Thêm mới</a></div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filter"> 
                            <form class="form-horizontal">
                                <fieldset>
                                    <legend>Tìm kiếm</legend>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Từ khóa</label>
                                            <div class="col-lg-9 col-md-8 col-sm-12">
                                                <input type="email" class="form-control" id="keyword">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Danh mục</label>
                                            <div class="col-lg-9 col-md-8">
                                                <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                    <option>cow</option>
                                                    <option>bull</option>
                                                    <option class="get-class" disabled>ox</option>
                                                    <optgroup label="test" data-subtext="another test">
                                                        <option>ASD</option>
                                                        <option selected>Bla</option>
                                                        <option>Ble</option>
                                                    </optgroup>
                                                  </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button type="button" class="btn btn-default btn-custom">Tìm</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div> <!-- end search -->

                    <div class="col-lg-12">
                        <div class="form-table">
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                        <th id="key" class="name column_name no-sort">
                                            <a class="asc" href="#">Mã <i class="fa fa-sort-asc"></i></a>
                                        </th>
                                        <th id="name">
                                            <a class="" href="#">Tên <i class="fa fa-sort-desc"></i></a>
                                        </th>
                                        <th class="description column_descripton">Mô tả</th>
                                        <th class="weight column_weight">Vị trí</th>
                                        <th class="quantity column_quantity">Số lượng</th>
                                        <th class="quantity column_quantity">Ngôn ngữ</th>
                                        <th class="status column_status">Trang thái</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>1</td>
                                        <td class="column-title column_name">
                                            <strong class="key-title">A Tên 1</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 1" data-slug="ten-1" data-weight="1" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">Mô tả</td>
                                        <td class="column_weight"><input value="1" name="updateweight[]" class="update_weight form-control"></td>
                                        <td class="column_quantity">200</td>
                                        <td class="column_quantity">en</td>
                                        <td class="column_status status"><a title="Hiển thị" class="fa fa-check-circle"></a></td>
                                    </tr>

                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>2</td>
                                        <td class="column-title column_name">
                                            <strong>C Tên 2</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 2" data-slug="ten-2" data-weight="2" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">Mô tả</td>
                                        <td class="column_weight"><input value="1" name="updateweight[]" class="update_weight form-control"></td>
                                        <td class="column_quantity">200</td>
                                        <td class="column_quantity">vi</td>
                                        <td class="column_status unstatus"><a title="Không hiển thị" class="fa fa-minus-circle"></a></td>
                                    </tr>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>3</td>
                                        <td class="column-title column_name">
                                            <strong>B Tên 3</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 3" data-slug="ten-3" data-weight="3" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">Mô tả</td>
                                        <td class="column_weight"><input value="1" name="updateweight[]" class="update_weight form-control"></td>
                                        <td class="column_quantity">200</td>
                                        <td class="column_quantity">en</td>
                                        <td class="column_status unstatus"><a title="Không hiển thị" class="fa fa-minus-circle"></a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="pager">
                <ul class="pagination">
                    <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="#" title="Lùi lại"><i class="fa fa-angle-left"></i></a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li class="active"><a>3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#" title="Tiếp theo"><i class="fa fa-angle-right"></i></a></li>
                    <li><a href="#" title="Trang Cuối"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.form-table .table>tbody>tr>td span.quick-edit a').on('click', function(){
             $(".form-table .table>tbody>tr").removeAttr('style');
             $(this).closest('tr').css('display', 'none');
             $('.edit-row').remove();
             var name = $(this).attr('data-name');
             var slug = $(this).attr('data-slug');
             var weight = $(this).attr('data-weight');
             var html = '';
             html +='<tr id="edit-1" class="edit-row">';
             html +='    <td colspan="8" class="">';
             html +='        <div class="column-qiuck-edit">';
             html +='            <div class="col-lg-12"><h2>Sửa nhanh</h2></div>';
             html +='            <div class="col-lg-12">';
             html +='                <div class="row">';
             html +='                    <div class="col-lg-6">';
             html +='                        <div class="form-group">';
             html +='                            <label for="name">Tên</label>';
             html +='                            <input type="text" class="form-control" value="'+name+'" id="name">';
             html +='                        </div>';
             html +='                        <div class="form-group">';
             html +='                            <label for="name">Slug</label>';
             html +='                            <input type="text" class="form-control" value="'+slug+'" id="slug">';
             html +='                        </div>';
             html +='                    </div>';
             html +='                </div>';
             html +='            </div>';
             html +='            <div class="col-lg-12">';
             html +='                <div class="row">';
             html +='                    <div class="col-lg-3">';
             html +='                        <div class="form-group">';
             html +='                            <label for="name">Vị trí</label>';
             html +='                            <input type="text" class="form-control" value="'+weight+'" id="weight">';
             html +='                        </div>';
             html +='                    </div>';
             html +='                    <div class="col-lg-3">';
             html +='                        <div class="form-group">';
             html +='                            <label>Danh mục cha</label>';
             html +='                            <select id="basic-1" class="selectpicker show-tick form-control" data-live-search="true">';
             html +='                                <option>cow</option>';
             html +='                                <option>bull</option>';
             html +='                                <option class="get-class" disabled>ox</option>';
             html +='                                <optgroup label="test" data-subtext="another test">';
             html +='                                    <option>ASD</option>';
             html +='                                    <option selected>Bla</option>';
             html +='                                    <option>Ble</option>';
             html +='                                </optgroup>';
             html +='                             </select>';
             html +='                        </div>';
             html +='                    </div>';
             html +='                </div>';
             html +='            </div>';
             html +='            <div class="col-lg-12">';
             html +='                <div class="row">';
             html +='                    <div class="col-lg-6">';
             html +='                        <div class="form-group">';
             html +='                            <button type="button" class="btn btn-default btn-back">Trở lại</button>';
             html +='                            <button type="button" class="btn btn-default btn-custom pull-right">Cập nhật</button>';
             html +='                        </div>';
             html +='                    </div>';
             html +='                </div>';
             html +='            </div>';
             html +='            <div class="col-lg-6"></div>';
             html +='        </div>';
             html +='    </td>';
             html +='</tr>';
             $(this).closest('tr').after(html);
             $('.selectpicker').selectpicker('refresh');
        });

        $('.form-table').on('click', '.table>tbody>tr .btn-back', function(){
             $(".form-table .table>tbody>tr").removeAttr('style');
             $('.edit-row').remove();
        });
   
  
});
</script>