<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Danh mục</h1>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <select class="form-control selected-custom">
                        <option value="">-- Chức năng --</option>
                        <option value="delete">Xóa vĩnh viễn</option>
                        <option value="published">Đăng</option>
                        <option value="unpublished">Tạm dừng</option>
                        <option value="update_weight">Cập nhật vị trí</option>
                    </select>
                    <button type="button" class="btn btn-default btn-custom apply">Thực hiện</button>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><a href="<?php echo $this->url('backend', array('controller' => 'category', 'action' => 'add')) ?>" class="btn btn-default btn-custom pull-right">Thêm mới</a></div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filter"> 
                            <form class="form-horizontal">
                                <fieldset>
                                    <legend>Tìm kiếm</legend>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Từ khóa</label>
                                            <div class="col-lg-9 col-md-8 col-sm-12">
                                                <input type="email" class="form-control" id="keyword">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button type="button" class="btn btn-default btn-custom">Tìm</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div> <!-- end search -->

                    <div class="col-lg-12">
                        <div class="form-table">
                            <?php if($list): ?>
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                        <th id="key" class="name column_name no-sort">
                                            <?php
                                                    if(isset($arrayParam['sort']) && $arrayParam['sort'] == 'id' && isset($arrayParam['order']) && !empty($arrayParam['order'])):
                                                        $class = $arrayParam['order'];
                                                        $link = $this->url($this->route, array('controller' => 'category', 'action' => 'index')). implode('', $paramSort);
                                                        $icon = 'fa-sort-'.$arrayParam['order'];
                                                    else:
                                                        $arrIdSort = $paramSort;
                                                        if(!isset($arrIdSort['sort']) || $arrIdSort['sort'] != 'id'){
                                                            if(isset($arrIdSort['sort']) && $arrIdSort['sort'] != 'id'){
                                                                unset($arrIdSort['sort']);
                                                            }
                                                            $arrId = array();
                                                            if(isset($arrIdSort['page'])){
                                                                $arrId['page'] = $paramSort['page'];
                                                            }
                                                            $arrId['sort'] = '/sort/id';
                                                            $arrIdSort = array_merge($arrId, $arrIdSort);
                                                        }
                                                        $arrIdSort['order'] = '/order/asc';
                                                        $class = '';
                                                        $link = $this->url($this->route, array('controller' => 'category', 'action' => 'index')). implode('', $arrIdSort);
                                                        $icon = 'fa-sort-desc';
                                                    endif;
                                                ?>
                                                <a class="<?php echo $class ?>" href="<?php echo $link; ?>">Mã <i class="fa <?php echo $icon; ?>"></i></a>
                                                
                                        </th>
                                        <th id="name">
                                            <?php
                                                    if(isset($arrayParam['sort']) && $arrayParam['sort'] == 'name' && isset($arrayParam['order']) && !empty($arrayParam['order'])):
                                                        $class = $arrayParam['order'];
                                                        $link = $this->url($this->route, array('controller' => 'category', 'action' => 'index')). implode('', $paramSort);
                                                        $icon = 'fa-sort-'.$arrayParam['order'];
                                                    else:
                                                        $paramFullnameSort = $paramSort;
       
                                                        if(!isset($paramFullnameSort['sort']) || $paramFullnameSort['sort'] != 'name'){
                                                            if(isset($paramFullnameSort['sort']) && $paramFullnameSort['sort'] != 'name'){
                                                                unset($paramFullnameSort['sort']);
                                                            }
                                                            $arrName = array();
                                                            if(isset($paramFullnameSort['page'])){
                                                                $arrName['page'] = $paramFullnameSort['page'];
                                                            }
                                                            $arrName['sort'] = '/sort/name';
                                                            $paramFullnameSort = array_merge($arrName, $paramFullnameSort);
                                                        }
                                                        
                                                        $paramFullnameSort['order'] = '/order/asc';
                                                        $class = '';
                                                        $link = $this->url($this->route, array('controller' => 'category', 'action' => 'index')). implode('', $paramFullnameSort);
                                                        $icon = 'fa-sort-desc';
                                                    endif;
                                                ?>
                                                <a class="<?php echo $class; ?>" href="<?php echo $link; ?>">Tên danh mục <i class="fa <?php echo $icon; ?>"></i></a>
                                        </th>
                                        <th class="description column_descripton">Mô tả</th>
                                        <th class="weight column_weight">Vị trí</th>
                                        <th class="quantity column_quantity">Số lượng</th>
                                        <th class="status column_status">Trang thái</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($list as $value): ?>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>
                                            <?php echo $value['id']; ?></td>
                                        <td class="column-title column_name">
                                            <strong class="key-title"><?php echo $value['name']; ?></strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a class="icon-edit" href="<?php echo $this->url('backend', array('controller' => 'category', 'action' => 'edit', 'id' => $value['id'])); ?>" title="Sửa"><i class="fa fa-pencil-square-o"></i></a>
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-id="<?php echo $value['id']; ?>"  title="Sửa nhanh" href="javascript:void(0)"><i class="fa fa-pencil-square"></i></a>
                                                </span>
                                                <span class="delete">
                                                    <a class="icon-delete" title="Xóa" data-id="<?php echo $value['id']; ?>" data-toggle="modal" data-target=".modal-delete-taxonomy" title="Delete"><i class="fa fa-times"></i></a>  
                                                </span>
                                                <span class="view">
                                                    <a href="#" title="Xem"><i class="fa fa-arrows-alt"></i></a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton"><?php echo $value['description']; ?></td>
                                        <td class="column_weight"><input type="number" min="0" value="<?php echo $value['sort']; ?>" name="sort[]" class="update_weight form-control"></td>
                                        <td class="column_quantity"><?php echo $value['count']; ?></td>
                                        <td class="column_status status">
                                            <?php echo ($value['status'] == 1)? '<a data-status='.json_encode(array('id' => $value['id'], 'status' => 1)).' href="javascript:void(0)" title="Hiển thị" class="active fa fa-check-circle"></a>': '<a data-status='.json_encode(array('id' => $value['id'], 'status' => 0)).' title="Không hiển thị" class="unactive fa fa-minus-circle"></a>'; ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>  
                                </tbody>
                            </table>
                            <?php else: ?>
                                <div class="alert alert-info" role="alert">Không tồn tại user nào. </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
			<?php
				echo $this->paginationControl($paginator, 'Elastic', 'partial/pagination.phtml',array('name' => 'backend','controller' => 'category','action' => 'index', 'routeParam' => $routeParam));
			?>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.form-table .table>tbody>tr>td span.quick-edit a').on('click', function(){
             $(".form-table .table>tbody>tr").removeAttr('style');
             $(this).closest('tr').css('display', 'none');
             $('.edit-row').remove();
             var name = $(this).attr('data-name');
             var slug = $(this).attr('data-slug');
             var weight = $(this).attr('data-weight');
             var html = '';
             html +='<tr id="edit-1" class="edit-row">';
             html +='    <td colspan="8" class="">';
             html +='        <div class="column-qiuck-edit">';
             html +='            <div class="col-lg-12"><h2>Sửa nhanh</h2></div>';
             html +='            <div class="col-lg-12">';
             html +='                <div class="row">';
             html +='                    <div class="col-lg-6">';
             html +='                        <div class="form-group">';
             html +='                            <label for="name">Tên</label>';
             html +='                            <input type="text" class="form-control" value="'+name+'" id="name">';
             html +='                        </div>';
             html +='                        <div class="form-group">';
             html +='                            <label for="name">Slug</label>';
             html +='                            <input type="text" class="form-control" value="'+slug+'" id="slug">';
             html +='                        </div>';
             html +='                    </div>';
             html +='                </div>';
             html +='            </div>';
             html +='            <div class="col-lg-12">';
             html +='                <div class="row">';
             html +='                    <div class="col-lg-3">';
             html +='                        <div class="form-group">';
             html +='                            <label for="name">Vị trí</label>';
             html +='                            <input type="text" class="form-control" value="'+weight+'" id="weight">';
             html +='                        </div>';
             html +='                    </div>';
             html +='                    <div class="col-lg-3">';
             html +='                        <div class="form-group">';
             html +='                            <label>Danh mục cha</label>';
             html +='                            <select id="basic-1" class="selectpicker show-tick form-control" data-live-search="true">';
             html +='                                <option>cow</option>';
             html +='                                <option>bull</option>';
             html +='                                <option class="get-class" disabled>ox</option>';
             html +='                                <optgroup label="test" data-subtext="another test">';
             html +='                                    <option>ASD</option>';
             html +='                                    <option selected>Bla</option>';
             html +='                                    <option>Ble</option>';
             html +='                                </optgroup>';
             html +='                             </select>';
             html +='                        </div>';
             html +='                    </div>';
             html +='                </div>';
             html +='            </div>';
             html +='            <div class="col-lg-12">';
             html +='                <div class="row">';
             html +='                    <div class="col-lg-6">';
             html +='                        <div class="form-group">';
             html +='                            <button type="button" class="btn btn-default btn-back">Trở lại</button>';
             html +='                            <button type="button" class="btn btn-default btn-custom pull-right">Cập nhật</button>';
             html +='                        </div>';
             html +='                    </div>';
             html +='                </div>';
             html +='            </div>';
             html +='            <div class="col-lg-6"></div>';
             html +='        </div>';
             html +='    </td>';
             html +='</tr>';
             $(this).closest('tr').after(html);
             $('.selectpicker').selectpicker('refresh');
        });

        $('.form-table').on('click', '.table>tbody>tr .btn-back', function(){
             $(".form-table .table>tbody>tr").removeAttr('style');
             $('.edit-row').remove();
        });
        
        // change status
        $(".form-table .table>tbody>tr>td.column_status a").on('click', function(){
            var data = $(this).attr('data-status');
            var loadData = jQuery.parseJSON(data);
            var obj = { 'id' : loadData.id, 'status': loadData.status };
            if (confirm('Bạn có muốn thay đổi trạng thái không?')) {
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'category', 'action' => 'changestatus')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(){
                        location.reload();
                    }    
               });
            }   
        });
        
        // delete category
        $(".form-table .table>tbody>tr>td .row-action span.delete a").on('click', function(){
            var category_id = $(this).attr('data-id');
            var obj = { 'category_id' : category_id};
            if (confirm('Bạn có muốn xóa không không?')) {
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url($this->route, array('controller' => 'category', 'action' => 'deletecategory')) ?>",
                    data: obj,
                    dataType: 'JSON',
                    beforeSend: function(){
                    },
                    success: function(data){
                        console.log(data);
                       // location.reload();
                    }    
               });
            }   
        });
   
  
});
</script>