<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CMS '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/libs/bootstrap-select/dist/css/bootstrap-select.min.css')
						->prependStylesheet($this->basePath() . '/libs/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/libs/bootstrap/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/libs/bootstrap-select/dist/js/bootstrap-select.min.js')
            ->prependFile($this->basePath() . '/libs/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.3.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
		<header>
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row">
							<div class="col-lg-12">
								<div class="row header">
									<div class="col-lg-6 col-xs-6">
										<div class="logo">Logo</div>
									</div>
									<div class="col-lg-6 col-xs-6 profile">
										<div class="user pull-right">
											<ul id="user-profile">
												<li>
													<a href="#"><var></var> User <span class="caret"></span></a>
													<ul id="user">
														<li><a href="#"><i class="icon iconprofile"></i> Tài khoản</a></li>
														<li><a href="#"><i class="icon iconlogout"></i> Đăng xuất</a></li>
													</ul>
												</li>
											</ul>
										</div>
										<div class="nav-mobile">
											<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false">
												<i class="fa fa-bars"></i>
											</button>
											
										</div>
									</div>
								</div>
							</div>
							<div class="col-lg-12 menu">
								<div class="menu-top">
									<nav class="nav-admin navbar navbar-default">
										<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
											<ul class="nav navbar-nav">
												<li><a href="#"><i class="icon dashboard"></i>Tổng quan</a>
												</li>
												<li>
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon iconproduct"></i> Hàng hóa <span class="caret"></span></a>
													<ul class="dropdown-menu">
														<li><a href="#"><i class="icon iconcategory"></i> Danh mục</a></li>
														<li><a href="#"><i class="icon iconcheckstore"></i> Kiểm kho</a></li>
													</ul>
												</li>
												<li>
													<a  href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon iconstore"></i> Giao dịch <span class="caret"></span></a>
													<ul class="dropdown-menu">
														<li><a href="#"><i class="icon iconinvoice"></i> Hóa đơn</a></li>
														<li><a href="#"><i class="icon iconrefund"></i> Trả hàng</a></li>
														<li><a href="#"><i class="icon iconpurchaseorders"></i> Nhập hàng</a></li>
														<li><a href="#"><i class="icon iconpurchasereturn"></i> Trả hàng nhập</a></li>
														<li><a href="#"><i class="icon iconfulfillment"></i> Chuyển hàng</a></li>
													</ul>
												</li>
												<li>
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon iconpartner"></i> Đối tác <span class="caret"></span></a>
													<ul class="dropdown-menu">
														<li><a href="#"><i class="icon iconcustomer"></i> Khách hàng</a></li>
														<li><a href="#"><i class="icon iconsupplier"></i> Nhà cung cấp</a></li>
														<li><a href="#"><i class="icon icontrademark"></i> Thương Hiệu</a></li>
													</ul>
												</li>
												<li>
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon iconreport"></i> Báo cáo <span class="caret"></span></a>
													<ul class="dropdown-menu">
														<li><a href="#"><i class="icon iconsale"></i> Bán hàng</a></li>
														<li><a href="#"><i class="icon iconproduct"></i> Hàng hóa</a></li>
														<li><a href="#"><i class="icon iconfinancial"></i> Tài chính </a></li>
														<li><a href="#"><i class="icon iconliabilities"></i> Công nợ</a></li>
														<li><a href="#"><i class="icon icondayend"></i> Cuối ngày</a></li>
													</ul>
												</li>
												<li>
													<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="icon iconconfig"></i> Thiết lập <span class="caret"></span></a>
													<ul class="dropdown-menu">
														<li><a href="#"><i class="icon iconuser"></i> Quản lý thành viên</a></li>
														<li><a href="#"><i class="icon iconstaff"></i> Quản lý nhân viên</a></li>
														<li><a href="#"><i class="icon iconshop"></i> Quản lý cửa hàng </a></li>
														<li><a href="#"><i class="icon iconsystem"></i> Phân quyền hệ thống</a></li>
														<li><a href="#"><i class="icon iconemail"></i> Quản lý Email</a></li>
													</ul>
												</li>
												<li><a href="#"> <i class="icon iconsale"></i>Bán hàng </a></li>
												<li><a href="#"><i class="icon iconhelp"></i> Hỗ trợ </a></li>
											</ul>
										</div>
									</nav><!-- /.navbar-collapse -->
								</div>
								
							</div>
						</div>
					</div>
				</div>

			</div>
        </header>
		
		<div class="main">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-6">
						<h1>Danh mục</h1>
					</div>
					<div class="col-lg-6">
						
					</div>
				</div>
			</div>
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="content">
							<div class="row">
								<div class="col-lg-12">
									<div class="filter">
										<fieldset>
											<legend>Tìm kiếm</legend>
											<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
												<div class="form-group">
													<label for="keyword" class="col-lg-2 col-md-2 col-sm-12 control-label">Từ khóa</label>
													<div class="col-lg-10 col-md-10 col-sm-12">
														<input type="email" class="form-control" id="keyword">
													</div>
												</div>
											</div>
											<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
												<div class="form-group">
													<label for="keyword" class="col-lg-2 col-md-2 col-sm-12 control-label">Danh mục</label>
													<div class="col-lg-10 col-md-10 col-sm-12">
														<select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
															<option>cow</option>
															<option>bull</option>
															<option class="get-class" disabled>ox</option>
															<optgroup label="test" data-subtext="another test">
																<option>ASD</option>
																<option selected>Bla</option>
																<option>Ble</option>
															</optgroup>
														  </select>
													</div>
												</div>
											</div>
											<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">sdfsf</div>
										</fieldset>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
        <?php echo $this->inlineScript() ?>
		<!--<div class="showcase"></div>-->
    </body>
</html>
