
<section class="statistics">
    <div class="container">
        <div class="row">
            <div class="col-md-12 statistics-title">
                <h2>Stable Forex Activity Statistics</h2>
            </div>
        </div>
        <ul class="row animated bounceIn">
            <li class="col-md-3">
                <div class="round-statistics">
                    <div class="item-statistics">
                        <p class="number-statistics">$3.500</p>
                        <p class="name-statistics">Running days</p>
                    </div>
                </div>
            </li>
            <li class="col-md-3">
                <div class="round-statistics">
                    <div class="item-statistics">
                        <p class="number-statistics">$3.500</p>
                        <p class="name-statistics">Running days</p>
                    </div>
                </div>
            </li>
            <li class="col-md-3">
                <div class="round-statistics">
                    <div class="item-statistics">
                        <p class="number-statistics">$3.500</p>
                        <p class="name-statistics">Running days</p>
                    </div>
                </div>
            </li>
            <li class="col-md-3">
                <div class="round-statistics">
                    <div class="item-statistics">
                        <p class="number-statistics">$3.500</p>
                        <p class="name-statistics">Running days</p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</section>