<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm nhân viên quản lý</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'category','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'user', 'action' => 'add')) ?>" id="form-add-user" method="post" enctype="multipart/form-data">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="content">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12">
									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Thông đăng nhập</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="name">Email <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="text" class="form-control" value="<?php echo isset($arrayParam['post']['email'])?$arrayParam['post']['email']:'' ?>" name="email" placeholder="Email">
															<p class="error"><?php echo isset($arrayParam['error']['email'])? $arrayParam['error']['email']:'' ?></p>
														</div>
													</div>
												</div>
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Mật khẩu <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" placeholder="Mật khẩu" name="password" value="<?php echo isset($arrayParam['post']['password'])?$arrayParam['post']['password']:'' ?>">
															<p class="error"><?php echo isset($arrayParam['error']['password'])? $arrayParam['error']['password']:'' ?></p>
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Nhập lại mật khẩu <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" placeholder="Mật khẩu" name="repassword" value="<?php echo isset($arrayParam['post']['repassword'])?$arrayParam['post']['repassword']:'' ?>">
															<p class="error"><?php echo isset($arrayParam['error']['repassword'])? $arrayParam['error']['repassword']:'' ?></p>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>

									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Thông cá nhân</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-6">
													<div class="form-group">
														<label for="icon">Ảnh đại diện <span class="help" data-toggle="tooltip" data-placement="right" title="This field is not empty.">?</span></label>
														<p class="help-block">File format jpg, JPG, png, PNG. (max-width: 100px, max-height: 100px).</p>
														<input type="file" class="form-control" id="icon" name="avartar" placeholder="Icon">
														<span id="error-image" class="error"></span>
													</div>
													<div id="view-image" class="form-group"></div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="fullname">Họ và tên <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="text" class="form-control" id="fullname" value="" name="fullname" placeholder="Họ và tên" data-name ="Email">
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="fullname">Tên hiển thị <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc nhập.">?</span></label>
															<input type="text" class="form-control" id="fullname" value="" name="name-alias" placeholder="Tên hiển thị">
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<div class="row">
																<div class="col-lg-12">
																	<label for="sex">Giới tính <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
																</div>
																<div class="col-lg-12">
																	<label class="radio-inline">
																		<input type="radio" name="sex" id="male" value="0"> Nam
																	</label>
																	<label class="radio-inline">
																		<input type="radio" name="sex" id="female" value="1"> Nữ
																	</label>
																	<label class="radio-inline">
																		<input type="radio" name="sex" id="other" value="2"> Khác
																	</label>
																</div>
															</div>
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="row">
															<div class="col-lg-12">
																<div class="box-language lang-vi">
																	<label for="day">Ngày tháng năm sinh</label>
																</div>
															</div>
															<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
																<div class="box-language lang-vi">
																	<input type="number" placeholder="Ngày" class="form-control" name="day">
																</div>
															</div>
															<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
																<div class="box-language lang-vi">
																	<input type="number" placeholder="Tháng" class="form-control" name="month">
																</div>
															</div>
															<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
																<div class="box-language lang-vi">
																	<input type="number" placeholder="Năm" class="form-control" name="year">
																</div>
															</div>
														</div>

													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="fullname">Địa chỉ <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc nhập.">?</span></label>
															<textarea name="address" class="form-control"></textarea>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-12">
									<?php if(isset($role)): ?>
									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Quyền truy cập</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<div class="checkbox">
																
																<?php foreach ($role as $key => $value): ?>
																<div class="radio">
																	<label>
																	  <input type="radio" name="role" id="role-<?php echo $value['id']; ?>" value="<?php echo $value['id']; ?>">
																	  <?php echo $value['role_name']; ?>
																	</label>
																</div>
																<?php endforeach; ?>
																
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<?php endif; ?>
									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Cài đặt trạng thái</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<div class="checkbox">
																<label>
																	<span><input checked value="1" type="checkbox" name="active"> Kích hoạt</span>
																</label>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="box-footer">
											<button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
											<button type="submit" class="btn btn-default btn-custom add">Tạo thành viên</button>                                     
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>