<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm nhân viên quản lý</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'category','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-language lang-vi">
                                        <div class="box-header"><h2>Thông đăng nhập</h2></div>
                                    </div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
														<label for="name">Email <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
														<input type="text" class="form-control" value="" name="email[vi]" placeholder="Email" data-name ="Email">
													</div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
														<label for="slug">Mật khẩu <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
                                                        <input type="password" class="form-control" placeholder="Mật khẩu" name="password[vi]">
													</div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <div class="box-language lang-vi">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <span><input checked type="checkbox" name="status[vi]"> Trạng thái</span>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                            <div class="box-language lang-en hidden">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <span><input checked type="checkbox" name="status[en]"> Published</span>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="box">
                                    <div class="box-language lang-vi">
                                        <div class="box-header"><h2>Thông cá nhân</h2></div>
                                    </div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
														<label for="fullname">Ảnh đại diện <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc nhập.">?</span></label>
                                                        <input type="file" class="form-control" id="fullname" value="" name="avartar[vi]" placeholder="Họ và tên" data-name ="Email">
													</div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
														<label for="fullname">Họ và tên <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
                                                        <input type="text" class="form-control" id="fullname" value="" name="fullname[vi]" placeholder="Họ và tên" data-name ="Email">
													</div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
													<div class="box-language lang-vi">
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <label for="sex">Giới tính <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
                                                            </div>
                                                            <div class="col-lg-12">
                                                                <label class="radio-inline">
                                                                    <input type="radio" name="sex[vi]" id="male" value="option1"> Nam
                                                                </label>
                                                                <label class="radio-inline">
                                                                    <input type="radio" name="sex[vi]" id="female" value="option2"> Nữ
                                                                </label>
                                                                <label class="radio-inline">
                                                                    <input type="radio" name="sex[vi]" id="other" value="option3"> Khác
                                                                </label>
                                                            </div>
                                                        </div>
														
                                                        
													</div>
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <div class="box-language lang-vi">
                                                                <label for="day">Ngày tháng năm sinh</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                                            <div class="box-language lang-vi">
                                                                <input type="number" placeholder="Ngày" class="form-control" name="day[vi]">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                                            <div class="box-language lang-vi">
                                                                <input type="number" placeholder="Tháng" class="form-control" name="month[vi]">
                                                            </div>
                                                        </div>
                                                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                                            <div class="box-language lang-vi">
                                                                <input type="number" placeholder="Năm" class="form-control" name="year[vi]">
                                                            </div>
                                                        </div>
                                                    </div>
													
                                                </div>
                                            </div>
                                            
                                            
                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <div class="box-language lang-vi">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <span><input checked type="checkbox" name="status[vi]"> Trạng thái</span>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                            <div class="box-language lang-en hidden">
                                                                <div class="checkbox">
                                                                    <label>
                                                                        <span><input checked type="checkbox" name="status[en]"> Published</span>
                                                                    </label>
                                                                </div>
                                                            </div>
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-language lang-vi">
                                        <div class="box-header"><h2>Cài đặt SEO</h2></div>
                                    </div>
                                    <div class="box-language lang-en hidden">
                                        <div class="box-header"><h2>Meta SEO</h2></div>
                                    </div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <div class="box-language lang-vi">
                                                        <label for="title">Tiêu đề SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                        <input type="text" class="form-control" name="metatitle[vi]" placeholder="Tiêu đề">
                                                    </div>
                                                    <div class="box-language lang-en hidden">
                                                        <label for="title">Meta title <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                        <input type="text" class="form-control" name="metatitle[en]" placeholder="Meta title">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <div class="box-language lang-vi">
                                                        <label for="keyword">Từ khóa SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                        <input type="text" class="form-control" name="metakeyword[vi]" placeholder="Từ khóa seo">
                                                    </div>
                                                    <div class="box-language lang-en hidden">
                                                        <label for="keyword">Meta keyword <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                        <input type="text" class="form-control" name="metakeyword[en]" placeholder="Meta keyword">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <div class="box-language lang-vi">
                                                        <label for="description">Mô tả SEO <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                        <textarea class="form-control" rows="3" name="metadescriptionp[vi]"></textarea>
                                                    </div>
                                                    <div class="box-language lang-en hidden">
                                                        <label for="description">Meta description <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc.">?</span></label>
                                                        <textarea class="form-control" rows="3" name="metadescriptionp[en]"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="box-footer">
                                            <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                            <button type="button" class="btn btn-default btn-custom add">Lưu</button>
                                            <button type="button" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>                                       
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>