<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Đổi mật khẩu</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'user','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'user', 'action' => 'changepassword', 'id' => $arrayParam['id'])) ?>" id="form-add-user" method="post" enctype="multipart/form-data">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="content">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12">
									<div class="box">
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Mật khẩu hiện tại <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" name="passwordold" value="<?php echo isset($arrayParam['post']['passwordold'])?$arrayParam['post']['passwordold']:'' ?>">
															<p class="error"><?php echo isset($arrayParam['error']['passwordold'])? $arrayParam['error']['passwordold']:'' ?></p>
														</div>
													</div>
												</div>
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Mật khẩu mới <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" placeholder="Mật khẩu" name="password" value="<?php echo isset($arrayParam['post']['password'])?$arrayParam['post']['password']:'' ?>">
															<p class="error"><?php echo isset($arrayParam['error']['password'])? $arrayParam['error']['password']:'' ?></p>
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Nhập lại mật khẩu mới <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" placeholder="Mật khẩu" name="repassword" value="<?php echo isset($arrayParam['post']['repassword'])?$arrayParam['post']['repassword']:'' ?>">
															<p class="error"><?php echo isset($arrayParam['error']['repassword'])? $arrayParam['error']['repassword']:'' ?></p>
														</div>
													</div>
												</div>
											</div>
										</div>
                                        <div class="box-footer">
											<button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
											<button type="submit" class="btn btn-default btn-custom add">Đổi mật khẩu</button>                                     
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

<script type="text/javascript">
    jQuery(document).ready(function($){
        // plugin validate image type
        (function($) {
            $.fn.checkFileType = function(options) {
                var defaults = {
                    allowedExtensions: [],
                    success: function() {},
                    error: function() {}
                };
                options = $.extend(defaults, options);

                return this.each(function() {

                    $(this).on('change keyup blue', function(e) {
                        var value = $(this).val(),
                            file = value.toLowerCase(),
                            extension = file.substring(file.lastIndexOf('.') + 1);
                            if ($.inArray(extension, options.allowedExtensions) == -1) {
                                options.error(
                                        {
                                            err: 'Định dạng file không cho phép.'
                                        }
                                    );
                                $(this).focus();
                            } else {
                                readURL(this);
                                options.success();
                            }
                    });

                });
            };
        })(jQuery);
        // get image review before update
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $image = '<img id="blah" src="'+ e.target.result +'"/>';
                   $("#view-image").empty().append($image);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#icon').checkFileType({
            allowedExtensions: ['jpg', 'jpeg','png'],
            success: function() {
            // code here
                $("#error-image").empty();
                $("#icon").removeClass('input-error');
            },
            error: function(e) {
                $("#icon").addClass('input-error');
                $("#error-image").empty().append(e.err);
                $("#view-image").empty();
            }
        });        
    });
</script>