<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Sửa thông tin tài khoản</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'user','action' => 'index')); ?>" class="btn btn-default btn-custom pull-right">Trở lại</a>
        </div>
    </div>
</div>
<form action="<?php echo $this->url('backend', array('controller' => 'user', 'action' => 'edit', 'id' => $arrayParam['id'])) ?>" id="form-add-user" method="post" enctype="multipart/form-data">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<div class="content">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-12">
									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Thông tin đăng nhập</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="name">Email <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="text" class="form-control" value="<?php echo isset($arrayParam['post']['email'])?$arrayParam['post']['email']:'' ?>" name="email" placeholder="Email">
															<p class="error"><?php echo isset($arrayParam['error']['email'])? $arrayParam['error']['email']:'' ?></p>
														</div>
													</div>
												</div>
<!--												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Mật khẩu <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" placeholder="Mật khẩu" name="password" value="<?php //echo isset($arrayParam['post']['password'])?$arrayParam['post']['password']:'' ?>">
															<p class="error"><?php //echo isset($arrayParam['error']['password'])? $arrayParam['error']['password']:'' ?></p>
														</div>
													</div>
												</div>-->

<!--												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="slug">Nhập lại mật khẩu <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="password" class="form-control" placeholder="Mật khẩu" name="repassword" value="<?php //echo isset($arrayParam['post']['repassword'])?$arrayParam['post']['repassword']:'' ?>">
															<p class="error"><?php //echo isset($arrayParam['error']['repassword'])? $arrayParam['error']['repassword']:'' ?></p>
														</div>
													</div>
												</div>-->
											</div>
										</div>
									</div>

									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Thông cá nhân</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-6">
													<div class="form-group">
														<label for="icon">Ảnh đại diện <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc. Định dạng file cho phép .jpg, .png (max-width: 400px, max-height: 400px)">?</span></label>
														<input type="file" class="form-control" id="icon" name="avartar" placeholder="Icon">
														<span id="error-image" class="error"></span>
                                                        <p class="error"><?php echo isset($arrayParam['error']['avartar'])? $arrayParam['error']['avartar']:'' ?></p>
													</div>
                                                    <div id="view-image" class="form-group">
                                                        <?php if((!empty($arrayParam['post']['avartar']) && !is_array($arrayParam['post']['avartar'])) || isset($arrayParam['error']['avartar']) ): ?>
                                                        <a data-id="<?php echo $arrayParam['id']; ?>" class="delete-avartar"></a>
                                                        <img src="<?php echo $this->basePath('/files/users/80x80/'.$arrayParam['post']['avartar']); ?>" />
                                                        <?php endif; ?>
                                                    </div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="fullname">Họ và tên <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
															<input type="text" class="form-control" id="fullname" value="<?php echo isset($arrayParam['post']['fullname'])?$arrayParam['post']['fullname']:'' ?>" name="fullname" placeholder="Họ và tên">
                                                            <p class="error"><?php echo isset($arrayParam['error']['fullname'])? $arrayParam['error']['fullname']:'' ?></p>
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="fullname">Tên hiển thị <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc nhập.">?</span></label>
															<input type="text" class="form-control" id="fullname" value="" name="name-alias" placeholder="Tên hiển thị">
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<div class="row">
																<div class="col-lg-12">
																	<label for="sex">Giới tính <span class="validation">*</span> <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường bắt buộc nhập.">?</span></label>
																</div>
																<div class="col-lg-12">
                                                                    
																	<label class="radio-inline">
																		<input type="radio" name="sex" <?php echo ((isset($arrayParam['post']['sex']) && $arrayParam['post']['sex'] ===0))?'checked':'' ?> id="male" value="0"> Nam
																	</label>
																	<label class="radio-inline">
																		<input type="radio" name="sex" <?php echo ((isset($arrayParam['post']['sex']) && $arrayParam['post']['sex'] ===1))?'checked':'' ?> id="female" value="1"> Nữ
																	</label>
																	<label class="radio-inline">
																		<input type="radio" name="sex" <?php echo ((isset($arrayParam['post']['sex']) && $arrayParam['post']['sex'] ===2))?'checked':'' ?> id="other" value="2"> Khác
																	</label>
                                                                    <p class="error"><?php echo isset($arrayParam['error']['sex'])? $arrayParam['error']['sex']:'' ?></p>
																</div>
															</div>
														</div>
													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="row">
															<div class="col-lg-12">
																<div class="box-language lang-vi">
																	<label for="day">Ngày tháng năm sinh</label>
																</div>
                                                                <p class="error"><?php echo isset($arrayParam['error']['date'])? $arrayParam['error']['date']:'' ?></p>
															</div>
															<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
																<div class="box-language lang-vi">
                                                                    <select class="form-control" name="day">
                                                                        <?php echo $day; ?>
                                                                    </select>
																</div>
															</div>
                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
																<div class="box-language lang-vi">
                                                                    <select class="form-control" name="month">
                                                                        <?php echo $month; ?>
                                                                    </select>
																</div>
															</div>
                                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
																<div class="box-language lang-vi">
                                                                    <select class="form-control" name="year">
                                                                        <?php echo $year; ?>
                                                                    </select>
																</div>
															</div>
														</div>

													</div>
												</div>

												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<label for="fullname">Địa chỉ <span class="help" data-toggle="tooltip" data-placement="right" title="Đây là trường không bắt buộc nhập.">?</span></label>
															<textarea name="address" class="form-control"><?php echo isset($arrayParam['post']['address'])?$arrayParam['post']['address']:'' ?></textarea>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-12">
									<?php if(isset($role)): ?>
									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Quyền truy cập</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
                                                            <p class="error"><?php echo isset($arrayParam['error']['role'])? $arrayParam['error']['role']:'' ?></p>
															<div class="checkbox">
																
																<?php foreach ($role as $key => $value): ?>
																<div class="radio">
																	<label>
																	  <input type="radio" <?php echo (isset($arrayParam['post']['role']) && $arrayParam['post']['role'] == $value['id'])?'checked':'' ?> name="role" id="role-<?php echo $value['id']; ?>" value="<?php echo $value['id']; ?>">
																	  <?php echo $value['role_name']; ?>
																	</label>
																</div>
																<?php endforeach; ?>
																
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
									<?php endif; ?>
									<div class="box">
										<div class="box-language lang-vi">
											<div class="box-header"><h2>Cài đặt trạng thái</h2></div>
										</div>
										<div class="box-body">
											<div class="row">
												<div class="col-lg-12">
													<div class="form-group">
														<div class="box-language lang-vi">
															<div class="checkbox">
																<label>
																	<span>
                                                                        <input type="hidden" name="active" value="0">
                                                                        <input type="checkbox" name="active" id="status" value="1" <?php echo (!isset($arrayParam['post']['active']))?'checked':((isset($arrayParam['post']['active'])) && $arrayParam['post']['active'] == 1)?'checked':'' ?>>
                                                                        Kích hoạt
                                                                    </span>
																</label>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="box-footer">
											<button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
											<button type="submit" class="btn btn-default btn-custom add">Tạo thành viên</button>                                     
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

<script type="text/javascript">
    jQuery(document).ready(function($){
        // xóa avartar
        $(".delete-avartar").on("click", function(){
            var id = $(this).attr("data-id");
            if(id != '')
            {
                var data_obj = { 'id' : id};
                $.ajax({
                    type:"POST",
                    url: "<?php echo $this->url('backend', array('controller' => 'user', 'action' => 'deleteavartar')) ?>",
                    data:data_obj,
                    dataType: 'JSON',
                    success: function(data){
                        console.log('saad');
                        console.log(data);
                        $("#view-image").empty().append(data.message);
                        setTimeout(function(){
                            $(".seccess").remove();
                        }, 2000);
                    }    
               });
            }  
        });
        // plugin validate image type
        (function($) {
            $.fn.checkFileType = function(options) {
                var defaults = {
                    allowedExtensions: [],
                    success: function() {},
                    error: function() {}
                };
                options = $.extend(defaults, options);

                return this.each(function() {

                    $(this).on('change keyup blue', function(e) {
                        var value = $(this).val(),
                            file = value.toLowerCase(),
                            extension = file.substring(file.lastIndexOf('.') + 1);
                            if ($.inArray(extension, options.allowedExtensions) == -1) {
                                options.error(
                                        {
                                            err: 'Định dạng file không cho phép.'
                                        }
                                    );
                                $(this).focus();
                            } else {
                                readURL(this);
                                options.success();
                            }
                    });

                });
            };
        })(jQuery);
        // get image review before update
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $image = '<img id="blah" src="'+ e.target.result +'"/>';
                   $("#view-image").empty().append($image);
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#icon').checkFileType({
            allowedExtensions: ['jpg', 'jpeg','png'],
            success: function() {
            // code here
                $("#error-image").empty();
                $("#icon").removeClass('input-error');
            },
            error: function(e) {
                $("#icon").addClass('input-error');
                $("#error-image").empty().append(e.err);
                $("#view-image").empty();
            }
        });        
    });
</script>