<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6">
            <h1>Thông tin user</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <a href="<?php echo $this->url('backend', array('controller' => 'user','action' => 'add')); ?>" class="btn btn-default btn-custom apply pull-right">Thêm mới</a>
            <a href="<?php echo $this->url('backend', array('controller' => 'user','action' => 'index')); ?>" class="btn btn-default btn-custom  pull-right">Trở lại</a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="infomation">
                            <div class="box">
                                <div class="box-language lang-vi">
                                    <div class="box-header"><h2>Thông cá nhân</h2></div>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <?php if($userInfo['fullname']): ?>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="box-language lang-vi">
                                                    <label for="fullname">Họ và tên: </label> <?php echo $userInfo['fullname'] ;?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif; ?>
                                        <?php if($userInfo['alias']): ?>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="box-language lang-vi">
                                                    <label for="fullname">Tên hiển thị: </label><?php echo $userInfo['alias'] ;?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif; ?>
                                        <?php if($userInfo['avartar']): ?>
                                        <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="icon">Ảnh đại diện:</label>
                                                    <div>
                                                        <img src="<?php echo $this->basePath('/files/users/80x80/'.$userInfo['avartar']); ?>" />
                                                    </div>
                                            </div>
                                            
                                            
                                        </div>
                                        <?php endif; ?>
                                        <?php if($userInfo['sex'] || $userInfo['sex'] == '0'): ?>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="box-language lang-vi">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <label for="sex">Giới tính:  </label> <?php echo ($userInfo['sex'] === '0')? 'Nữ':(($userInfo['sex'] === '1')? 'Nam': 'Khác');?>
                                                        </div>
                                                        
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif; ?>
                                        <?php if($userInfo['birthday']): ?>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="box-language lang-vi">
                                                            <label for="day">Ngày sinh: </label> <?php echo date('d/m/Y', $userInfo['birthday']); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                       <?php endif; ?>                                                     
                                        <?php if($userInfo['address']): ?>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="box-language lang-vi">
                                                    <label for="fullname">Địa chỉ: </label> <?php echo $userInfo['address']; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif; ?>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="infomation">
                            <div class="box">
                                <div class="box-language lang-vi">
                                    <div class="box-header"><h2>Thông tài khoản</h2></div>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <?php if($userInfo['email']): ?>
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="box-language lang-vi">
                                                    <label for="fullname">Email: </label> <?php echo $userInfo['email']; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif; ?>  
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <div class="box-language lang-vi">
                                                    <label for="fullname">Mật khẩu</label> ******
                                                </div>
                                            </div>
                                        </div>
                                        
                                        
                                    </div>
                                </div>
                                <div class="box-footer">
                                    <a href="<?php echo $this->url('backend', array('controller' => 'user', 'action' => 'edit', 'id' => $id)); ?>" class="btn btn-default btn-custom add">sửa</a>                                     
                                    </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
