<section class="payment">
    <div class="container animated fadeInLeft">
        <div class="row">
            <div class="col-md-8">
                <ul class="row">
                    <li class="col-md-3"><img src="<?php echo $this->basePath('default/payment-1.png'); ?>" alt=""></li>
                    <li class="col-md-3"><img src="<?php echo $this->basePath('default/payment-2.png'); ?>" alt=""></li>
                    <li class="col-md-3"><img src="<?php echo $this->basePath('default/payment-3.png'); ?>" alt=""></li>
                    <li class="col-md-3"><img src="<?php echo $this->basePath('default/payment-4.png'); ?>" alt=""></li>
                </ul>
            </div>
            <div class="col-md-4 register-now">
                <p>Start your investment today</p>
                <a data-toggle="modal" data-target="#register">Create an account now <i class="fa fa-angle-double-right"></i></a>
            </div>
        </div>
    </div>
</section>