<section class="change-password">
	<div class="container">
		<div class="row">
			<div class="col-md-12"><h1>Change Password</h1></div>
			<div class="col-md-12">
				<form class="form-horizontal" method="post" enctype="multipart/form-data" action="<?php echo $this->url('changepassword', array('controller' => 'user', 'action' => 'changepassword')) ?>">
					<div class="form-group">
						<p class="error"><?php echo isset($arrayParam['post']['error'])? $arrayParam['post']['error']:'' ?></p>
					</div>
					<div class="form-group">
				    <label for="password-old" class="col-sm-2 control-label">Password old</label>
				    <div class="col-sm-10">
							<input type="password" value="<?php echo isset($arrayParam['post']['password-old'])?$arrayParam['post']['password-old']:'' ?>" name="password-old" class="form-control" id="password-old">
							<p class="error"><?php echo isset($arrayParam['error']['passwordold'])? $arrayParam['error']['passwordold']:'' ?></p>
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="password-new" class="col-sm-2 control-label">Password New</label>
				    <div class="col-sm-10">
							<input type="password" value="<?php echo isset($arrayParam['post']['password-new'])?$arrayParam['post']['password-new']:'' ?>" name="password-new" class="form-control" id="password-new">
							<p class="error"><?php echo isset($arrayParam['error']['passwordnew'])? $arrayParam['error']['passwordnew']:'' ?></p>
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="confirm-password-new" class="col-sm-2 control-label">Confirm password new</label>
				    <div class="col-sm-10">
							<input type="password" value="<?php echo isset($arrayParam['post']['confirm-password-new'])?$arrayParam['post']['confirm-password-new']:'' ?>" name="confirm-password-new" class="form-control" id="confirm-password-new">
							<p class="error"><?php echo isset($arrayParam['error']['repasswordnew'])? $arrayParam['error']['repasswordnew']:'' ?></p>
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-2 col-sm-10">
				      <button type="submit" class="btn btn-default">Send</button>
				    </div>
				  </div>
				</form>
		</div>
	</div>
</section>