<section class="user-profile">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="topmenu">
					<nav class="navbar navbar-default">
					   
				      	<!-- Collect the nav links, forms, and other content for toggling -->
				      	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				         	<ul class="nav navbar-nav">
				            	<li>
				            		<a href="#">
				            			<span><i class="icon-user"></i></span>
				            			<span>Account</span></a>
				            	</li>
				            	<li class="dropdown">
				            		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				            			<span><i class="icon-total-deposit"></i></span>
				            			<span>Make deposit</span>
				            		</a>
				            		<ul class="dropdown-menu">
				                  		<li><a href="#">Action</a></li>
				                  		<li><a href="#">Another action</a></li>
				                  		<li><a href="#">Something else here</a></li>
				                  		<li><a href="#">Separated link</a></li>
				                  		<li><a href="#">One more separated link</a></li>
				               		</ul>
				            	</li>
				            	<li class="dropdown">
				               		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
				               			<span><i class="icon-history"></i></span>
				               			<span>Account history</span>
				               		</a>
				               		<ul class="dropdown-menu">
				                  		<li><a href="#">Action</a></li>
				                  		<li><a href="#">Another action</a></li>
				                  		<li><a href="#">Something else here</a></li>
				                  		<li><a href="#">Separated link</a></li>
				                  		<li><a href="#">One more separated link</a></li>
				               		</ul>
				            	</li>
				            	<li class="dropdown">
				            		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				            			<span><i class="icon-total-withdraw"></i></span>
				            			<span>Withdraw</span>
				            		</a>
				            		<ul class="dropdown-menu">
				                  		<li><a href="#">Action</a></li>
				                  		<li><a href="#">Another action</a></li>
				                  		<li><a href="#">Something else here</a></li>
				                  		<li><a href="#">Separated link</a></li>
				                  		<li><a href="#">One more separated link</a></li>
				               		</ul>
				            	</li>
				            	<li class="dropdown">
				            		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				            			<span><i class="icon-last-deposit"></i></span>
				            			<span>Your deposit</span>
				            		</a>
				            		<ul class="dropdown-menu">
				                  		<li><a href="#">Action</a></li>
				                  		<li><a href="#">Another action</a></li>
				                  		<li><a href="#">Something else here</a></li>
				                  		<li><a href="#">Separated link</a></li>
				                  		<li><a href="#">One more separated link</a></li>
				               		</ul>
				            	</li>
				         	</ul>
				      	</div>
				      <!-- /.navbar-collapse -->
					  
					   <!-- /.container-fluid -->
					</nav>
				</div><!--end topmenu-->
			</div>
			<div class="col-md-12">
				<div class="content-user-profile">
					<ul class="statistics-user-profile">
						<li>
							<p><span class="icon-balance"></span></p>
							<p class="name">Blance</p>
							<p class="price">$2.70</p>
						</li>
						<li>
							<p><span class="icon-total-deposit"></span></p>
							<p class="name">Total deposit</p>
							<p class="price">$2.70</p>
						</li>
						<li>
							<p><span class="icon-total-withdraw"></span></p>
							<p class="name">Total withdraw</p>
							<p class="price">$2.70</p>
						</li>
						<li>
							<p><span class="icon-last-deposit"></span></p>
							<p class="name">Last deposit</p>
							<p class="price">$2.70</p>
						</li>
						<li>
							<p><span class="icon-total-bonus"></span></p>
							<p class="name">Total bonus</p>
							<p class="price">$2.70</p>
						</li>
					<div class="clearfix"></div>
					</ul>
					<div class="wrap-info-user">
						<div class="col-md-5">
							<form class=form-user-account>
						  		<fieldset>
						  			<legend>User Account</legend>
						  			<ul>
						  				<li>
						  					<span class="icon-user"></span>
						  					<span class="username">Nguyen Van A <var>/012345</var></span>
						  				</li>
						  				<li>
						  					<span class="icon-edit"></span>
						  					<span>
						  						<a href="#">Edit account</a>	
						  					</span>
						  				</li>
						  				<li>
						  					<span class="icon-logout"></span>
						  					<span>
						  						<a href="#">Logout</a>	
						  					</span>
						  				</li>
						  			</ul>
						    	</fieldset>
						    	<div class="total-deposit">
						    		<span class="total">Total deposit:</span>
						    		<span class="price">$50.000</span>
						    	</div>
							</form>
						</div>
						<div class="col-md-7">
							<form class="form-user-account form-user-info">
						  		<fieldset>
						  			<legend>User Information</legend>
						  			<ul>
						  				<li>
						  					<span class="left-name"><var>User:</var></span>
						  					<span class="right-info">Nguyen Van A</span>
						  				</li>
						  				<li>
						  					<span class="left-name"><var>Full name:</var></span>
						  					<span class="right-info">eregister14@yahoo.com</span>
						  				</li>
						  				<li>
						  					<span class="left-name"><var>Your email:</var></span>
						  					<span class="right-info">eregister14@yahoo.com</span>
						  				</li>
						  				<li>
						  					<span class="left-name"><var>Your referral link:</var></span>
						  					<span class="right-info">
						  						<a href="#">https://honorr.biz/?agent_id=HONOR12486</a>
						  					</span>
						  				</li>
						  				
						  			</ul>
						    	</fieldset>
							</form>
						</div>
					<div class="clearfix"></div>
					</div>

					<div class="wrap-logo-payment">
						<div class="col-md-3">
							<img src="default/logo-payment-1.png" alt="">
							<p>$27.700</p>
						</div>
						<div class="col-md-3">
							<img src="default/logo-payment-2.png" alt="">
							<p>$27.700</p>
						</div>
						<div class="col-md-3">
							<img src="default/logo-payment-3.png" alt="">
							<p>$27.700</p>
						</div>
						<div class="col-md-3">
							<img src="default/logo-payment-4.png" alt="">
							<p>$27.700</p>
						</div>
					</div>
				<div class="clearfix"></div>
				</div><!--end content-user-profile-->
			</div>
			
		</div>
	</div>
</section>