<p class="title-related">Related news</p>
  <ul class="news-related">
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
    <li>
      <a href="#">
        <img src="<?php echo $this->basePath('default/demo.jpg'); ?>" alt="">
      </a>
      <h2><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</a></h2>
      <p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
    </li>
  </ul>