<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h1>Thêm thương hiệu</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <button type="button" class="btn btn-default btn-custom pull-right">Trở lại</button>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Thông tin chung</h2></div>
                                    <div class="box-body">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="name">Tên thương hiệu</label>
                                                    <input type="text" data-toggle="tooltip" data-placement="top" title="Nhập tên thương hiệu" class="form-control" id="name" placeholder="Tên">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="slug">Slug</label>
                                                    <input type="text" data-toggle="tooltip" data-placement="top" title="Nhập alias cho thương hiệu" class="form-control" id="slug" placeholder="Slug">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="image_gallery">Logo</label>
                                                    <input type="file" class="form-control" id="image_gallery">
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="form-group">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input type="checkbox" checked="checked" name="status"> Trạng thái
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
   
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="box">
                                    <div class="box-header"><h2>Cài đặt SEO</h2></div>
                                    <div class="box-body box-bs">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="title">Tiêu đề</label>
                                                    <input type="text" class="form-control" id="title" placeholder="Tiêu đề" data-toggle="tooltip" data-placement="top" title="Nhập tiêu đề SEO">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="keyword">Từ khóa</label>
                                                        <input type="text" class="form-control" id="keyword" placeholder="keyword" placeholder="Tiêu đề" data-toggle="tooltip" data-placement="top" title="Nhập từ khóa SEO">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <label for="description">Mô tả</label>
                                                    <textarea class="form-control" rows="3" name="description" placeholder="Tiêu đề" data-toggle="tooltip" data-placement="top" title="Nhập mô tả SEO"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="box box-botton">
                                    <div class="box-footer">
                                        <button type="reset" class="btn btn-default btn-back add">Nhập lại</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu</button>
                                        <button type="button" class="btn btn-default btn-custom add">Lưu & Thêm mới</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-category modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm nhóm hàng</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="keyword">Tên nhóm</label>
                        <input type="text" class="form-control" id="category_ajax" placeholder="Tên nhóm">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="form-group">
                            <label for="quantity">Nhóm cha</label>
                            <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                <option>cow</option>
                                <option>bull</option>
                                <option class="get-class" disabled>ox</option>
                                <optgroup label="test" data-subtext="another test">
                                    <option>ASD</option>
                                    <option selected>Bla</option>
                                    <option>Ble</option>
                                </optgroup>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>

<div class="modal fade bs-store modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm kho hàng</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="keyword">Tên kho</label>
                        <input type="text" class="form-control" id="category_ajax" placeholder="Tên kho hàng">
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>

<div class="modal fade bs-trademark modal-custom" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
            <h4 class="modal-title" id="gridSystemModalLabel">Thêm thương hiệu</h4>
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="form-group">
                        <label for="keyword">Tên thương hiệu</label>
                        <input type="text" class="form-control" id="category_ajax" placeholder="Tên thương hiệu">
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-back add" data-dismiss="modal">Bỏ qua</button>
            <button type="button" class="btn btn-primary btn-custom add">Lưu</button>
        </div>
    </div>
  </div>
</div>