<section class="section-breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
					<li><a href="#">Home</a><span></span></li>
				  	<li class="active">News</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<section class="block-news">
	<div class="container">
		<ul class="row list-news">
      <?php if($list): ?>
      <?php foreach ($list as $value): ?>
			<li class="col-md-3">
        <p><a title="<?php echo $value['name']; ?>" href="<?php echo $this->url('news-detail', array('controller' => 'news', 'action' => 'detail', 'slug' => $value['slug'])); ?>">
            <img title="<?php echo $value['name']; ?>" alt="<?php echo $value['name']; ?>" src="<?php echo $this->basePath('files/news/272x181/'.$value['image']); ?>">
          </a>
        </p>
            <h2><a href="<?php echo $this->url('news-detail', array('controller' => 'news', 'action' => 'detail', 'slug' => $value['slug'])); ?>"><?php echo $value['name']; ?></a></h2>
				<p><?php echo $value['excerpt']; ?></p>
				<p class="readmore"><a href="<?php echo $this->url('news-detail', array('controller' => 'news', 'action' => 'detail', 'slug' => $value['slug'])); ?>">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
      <?php endforeach; ?>
      <?php else: ?>
      <?php endif; ?>
		</ul>
	</div>
</section>
<?php if($list): ?>
<section class="paging">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="paging">
					<nav>
					  <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination_news.phtml', array('name' => 'frontend','controller' => 'news','action' => 'index')); ?>
					</nav>
				</div>
			</div>
		</div>
	</div>
</section>
<?php endif; ?>
<?php //echo $this->statitics(); ?>
<?php //echo $this->payment(); ?>
