<section class="section-breadcrumb">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
					<li><a href="#">Home</a><span></span></li>
				  	<li class="active">News</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<section class="block-news">
	<div class="container">
		<ul class="row list-news">
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"<a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p class="readmore"><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
			<li class="col-md-3">
				<p><img src="<?php echo $this->basePath('default/demo.jpg'); ?>"></p>
				<h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, ex! Facilis, quam.</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis alias qui totam praesentium quam esse quod sapiente eaque numquam magnam.</p>
				<p><a href="#">Read more <i class="fa fa-angle-double-right"></i></a>
			</li>
		</ul>
	</div>
</section>
<section class="paging">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="paging">
					<nav>
					  <ul class="pagination">
					    <li>
					      <a href="#" aria-label="Previous">
					        <span aria-hidden="true">&laquo;</span>
					      </a>
					    </li>
					    <li><a href="#">1</a></li>
					    <li><a href="#">2</a></li>
					    <li class="active"><a href="#">3</a></li>
					    <li><a href="#">4</a></li>
					    <li><a href="#">5</a></li>
					    <li>
					      <a href="#" aria-label="Next">
					        <span aria-hidden="true">&raquo;</span>
					      </a>
					    </li>
					  </ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</section>

<?php //echo $this->statitics(); ?>
<?php //echo $this->payment(); ?>
