<?php echo $this->slider(); ?>
<section class="block-about-us">
    <div class="container">
        <div class="col-md-12"><h2>About us</h2></div>
        <div class="col-md-4"><img src="<?php echo $this->basePath('default/about-us.png'); ?>"></div>
        <div class="col-md-5">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="col-md-3">
            <div class="item-security"><img src="<?php echo $this->basePath('default/ddos.png'); ?>"></div>
            <div class="item-security"><img src="<?php echo $this->basePath('default/ssl.png'); ?>"></div>
            <div class="item-security"><img src="<?php echo $this->basePath('default/sitelock.png'); ?>"></div>
        </div>
    </div>
</section>
<section class="payment">
    <div class="container">
        <div class="row"></div>
    </div>
</section>
