<?php echo $this->slider(); ?>
<section class="block-deposit">
    <div class="container">
        <div class="row">
            <div class="col-md-12 deposit-12">
                <div class="block-deposit-title">
                    <h1>Investment packages</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt asperiores, eveniet fugit harum, ut iure.</p>
                </div>
            </div>
            <div class="col-md-12 rotate">
                <div class="item">
                    <div class="item-logo"><img src="<?php echo $this->basePath('img/logo.png'); ?>"></div>
                    <div class="item-blance">
                        <ul>
                            <li class="bound-animated animated fadeInLeft">
                                <div class="description">
                                    <p class="name">Blance</p>
                                    <p class="price">$27.000</p>
                                </div>
                                <div class="blance blance-1"><i class="fa fa-camera"></i></div>

                            </li>
                            <li class="bound-animated animated fadeInLeft">
                                <div class="description">
                                    <p class="name">Total deposit</p>
                                    <p class="price">$27.000</p>
                                </div>
                                <div class="blance blance-1"><i class="fa fa-camera"></i></div>
                            </li>
                            <li class="bound-animated animated rollIn">
                                <div class="blance blance-1"><i class="fa fa-camera"></i></div>
                                <div class="description">
                                    <p class="name">Total withdrow</p>
                                    <p class="price">$27.000</p>
                                </div>
                            </li>
                            <li class="bound-animated animated fadeInRight">
                                <div class="blance blance-1"><i class="fa fa-camera"></i></div>
                                <div class="description">
                                    <p class="name">Last deposit</p>
                                    <p class="price">$275.000</p>
                                </div>
                            </li>
                            <li class="bound-animated animated fadeInRight">
                                <div class="blance blance-1"><i class="fa fa-camera"></i></div>
                                <div class="description">
                                    <p class="name">Total bonus</p>
                                    <p class="price">$270.000</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="block-about-us">
    <div class="container">
        <div class="col-md-12 animated fadeInUp"><h2>About us</h2></div>
        <div class="col-md-4 animated fadeInUp"><img src="<?php echo $this->basePath('default/about-us.png'); ?>"></div>
        <div class="col-md-5 animated fadeInUp">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. </p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="col-md-3 animated fadeInRight">
            <div class="item-security"><img src="<?php echo $this->basePath('default/ddos.png'); ?>"></div>
            <div class="item-security"><img src="<?php echo $this->basePath('default/ssl.png'); ?>"></div>
            <div class="item-security"><img src="<?php echo $this->basePath('default/sitelock.png'); ?>"></div>
        </div>
    </div>
</section>
<?php echo $this->statitics(); ?>
<?php echo $this->payment(); ?>




