<div class="container-fluid">
    <div class="row function-title">
        <div class="col-lg-12">
            <h1>Danh mục</h1>
        </div>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <select class="form-control selected-custom">
                        <option>----</option>
                        <option>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select>
                    <button type="button" class="btn btn-default btn-custom apply">Thực hiện</button>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><button type="button" class="btn btn-default btn-custom pull-right">Thêm mới</button></div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="filter"> 
                            <form class="form-horizontal">
                                <fieldset>
                                    <legend>Tìm kiếm</legend>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Từ khóa</label>
                                            <div class="col-lg-9 col-md-8 col-sm-12">
                                                <input type="email" class="form-control" id="keyword">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-5 col-md-5">
                                        <div class="form-group">
                                            <label for="keyword" class="col-lg-3 col-md-4 control-label">Danh mục</label>
                                            <div class="col-lg-9 col-md-8">
                                                <select id="basic" class="selectpicker show-tick form-control" data-live-search="true">
                                                    <option>cow</option>
                                                    <option>bull</option>
                                                    <option class="get-class" disabled>ox</option>
                                                    <optgroup label="test" data-subtext="another test">
                                                        <option>ASD</option>
                                                        <option selected>Bla</option>
                                                        <option>Ble</option>
                                                    </optgroup>
                                                  </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <div class="col-lg-12">
                                            <div class="form-group">
                                                <button type="button" class="btn btn-default btn-custom">Tìm</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div> <!-- end search -->

                    <div class="col-lg-12">
                        <div class="form-table">
                            <table id="table-data" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th id="all" class="all"><input type="checkbox" class="form-all"></th>
                                        <th id="key" class="name column_name no-sort">
                                            <a href="#">Mã <i class="fa fa-sort-asc"></i></a>
                                        </th>
                                        <th id="name">
                                            <a class="desc" href="#">Tên <i class="fa fa-sort-desc"></i></a>
                                        </th>
                                        <th class="description column_descripton">Mô tả</th>
                                        <th class="weight column_weight">Vị trí</th>
                                        <th class="quantity column_quantity">Số lượng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>1</td>
                                        <td class="column-title column_name">
                                            <strong class="key-title">A Tên 1</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 1" data-slug="ten-1" data-weight="1" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">Mô tả</td>
                                        <td class="column_weight">1</td>
                                        <td class="column_quantity">200</td>
                                    </tr>

                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>2</td>
                                        <td class="column-title column_name">
                                            <strong>C Tên 2</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 2" data-slug="ten-2" data-weight="2" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">Mô tả</td>
                                        <td class="column_weight">1</td>
                                        <td class="column_quantity">200</td>
                                    </tr>
                                    <tr>
                                        <td><input type="checkbox" class="form-checkbox check-all"></td>
                                        <td>3</td>
                                        <td class="column-title column_name">
                                            <strong>B Tên 3</strong>
                                            <div class="row-action">
                                                <span class="edit">
                                                    <a href="#">Sửa</a> | 
                                                </span>
                                                <span class="quick-edit">
                                                    <a data-name="Tên 3" data-slug="ten-3" data-weight="3" href="javascript:void(0)">Sửa nhanh</a> | 
                                                </span>
                                                <span class="delete">
                                                    <a href="#">Xóa</a> | 
                                                </span>
                                                <span class="view">
                                                    <a href="#">Xem</a>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="column_descripton">Mô tả</td>
                                        <td class="column_weight">1</td>
                                        <td class="column_quantity">200</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="pager">
                <ul class="pagination">
                    <li><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li><a href="#" title="Lùi lại"><i class="fa fa-angle-left"></i></a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li class="active"><a>3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#" title="Tiếp theo"><i class="fa fa-angle-right"></i></a></li>
                    <li><a href="#" title="Trang Cuối"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>

            </div>
        </div>
    </div>
</div>